import type { Pool } from "pg";
import type {
  CollectionDefinition,
  CollectionFieldDefinition,
  TemplateDefinition,
} from "@/lib/template/contracts";
import { validateTemplateDefinition } from "@/lib/template/validateTemplateDefinition";

const IDENTIFIER = /^[a-z_][a-z0-9_]{0,62}$/;

const FIELD_SQL_TYPE: Record<CollectionFieldDefinition["type"], string> = {
  string: "varchar(500)",
  text: "text",
  integer: "bigint",
  decimal: "numeric",
  boolean: "boolean",
  date: "date",
  datetime: "timestamptz",
  json: "jsonb",
};

export class AppSchemaError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "AppSchemaError";
  }
}

const quoteIdentifier = (value: string): string => {
  if (!IDENTIFIER.test(value)) {
    throw new AppSchemaError(`Unsafe database identifier '${value}'`);
  }
  return `"${value}"`;
};

export function createCollectionTableSql(
  collection: CollectionDefinition,
): string {
  if (!collection.fields.length) {
    throw new AppSchemaError(`Collection '${collection.id}' has no fields`);
  }
  const primaryKeys = collection.fields.filter((field) => field.primaryKey);
  if (!primaryKeys.length) {
    throw new AppSchemaError(`Collection '${collection.id}' has no primary key`);
  }

  const singleIntegerPrimary = primaryKeys.length === 1 && primaryKeys[0].type === "integer";
  const columns = collection.fields.map((field) => {
    const name = quoteIdentifier(field.id);
    const type = FIELD_SQL_TYPE[field.type];
    const identity = singleIntegerPrimary && field.primaryKey
      ? " GENERATED BY DEFAULT AS IDENTITY"
      : "";
    const nullable = field.required || field.primaryKey ? " NOT NULL" : "";
    const primary = primaryKeys.length === 1 && field.primaryKey ? " PRIMARY KEY" : "";
    return `${name} ${type}${identity}${nullable}${primary}`;
  });
  if (primaryKeys.length > 1) {
    columns.push(
      `PRIMARY KEY (${primaryKeys.map((field) => quoteIdentifier(field.id)).join(", ")})`,
    );
  }
  const fieldIds = new Set(collection.fields.map((field) => field.id));
  if (!fieldIds.has("created_at")) {
    columns.push('"created_at" timestamptz NOT NULL DEFAULT now()');
  }
  if (!fieldIds.has("updated_at")) {
    columns.push('"updated_at" timestamptz NOT NULL DEFAULT now()');
  }

  return `CREATE TABLE IF NOT EXISTS public.${quoteIdentifier(collection.tableName)} (${columns.join(", ")})`;
}

export interface ApplyAppSchemaResult {
  revision: string;
  tables: string[];
}

/** Additive first provision: creates missing tables and records the Template revision. */
export async function applyAppSchema(
  pool: Pool,
  definition: TemplateDefinition,
): Promise<ApplyAppSchemaResult> {
  const validation = validateTemplateDefinition(definition);
  if (!validation.valid) {
    throw new AppSchemaError(
      `Template definition is invalid: ${validation.issues
        .map((issue) => `${issue.path}: ${issue.message}`)
        .join("; ")}`,
    );
  }
  const revision = definition.template.revision;
  if (!revision) throw new AppSchemaError("Published Template revision is required");

  const client = await pool.connect();
  try {
    await client.query("BEGIN");
    await client.query("CREATE EXTENSION IF NOT EXISTS pgcrypto");
    for (const collection of definition.collections) {
      await client.query(createCollectionTableSql(collection));
    }
    await client.query(
      `INSERT INTO sys.structure_revisions (revision, definition)
       VALUES ($1, $2::jsonb)
       ON CONFLICT (revision) DO NOTHING`,
      [revision, JSON.stringify(definition)],
    );
    await client.query("COMMIT");
    return {
      revision,
      tables: definition.collections.map((collection) => collection.tableName),
    };
  } catch (error) {
    await client.query("ROLLBACK");
    throw error;
  } finally {
    client.release();
  }
}
