import { createHash } from 'node:crypto';
import { getCoreDb } from './coreDb';
import { getTenantDb } from './tenantDb';

type Node = { props?: Record<string, unknown>; children?: Node[] };
const standardColumns: Record<string, string[]> = {
  users: ['id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY', 'email varchar(255) UNIQUE', 'full_name varchar(255)', 'role varchar(80)', 'status integer DEFAULT 1', 'created_at timestamptz DEFAULT now()', 'updated_at timestamptz DEFAULT now()'],
  cms_file_category: ['id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY', 'name varchar(255) NOT NULL'],
  cms_file: ['id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY', 'cms_file_category_id bigint', 'name varchar(500)', 'file_path text', 'status integer DEFAULT 1', 'created_at timestamptz DEFAULT now()', 'updated_at timestamptz DEFAULT now()'],
  cms_post: ['id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY', 'cms_category_id bigint', 'name varchar(500)', 'description text', 'image text', 'status integer DEFAULT 1', 'publish_at timestamptz', 'created_at timestamptz DEFAULT now()', 'updated_at timestamptz DEFAULT now()'],
  cms_page: ['id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY', 'name varchar(500)', 'description text', 'slug varchar(255)', 'status integer DEFAULT 1', 'created_at timestamptz DEFAULT now()', 'updated_at timestamptz DEFAULT now()'],
  cms_menu: ['id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY', 'parent_id bigint', 'menu_name varchar(255)', 'url text', 'icon varchar(255)', 'position varchar(40)', 'sort_order integer DEFAULT 0', 'status integer DEFAULT 1', 'created_at timestamptz DEFAULT now()', 'updated_at timestamptz DEFAULT now()'],
  cms_slide: ['id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY', 'name varchar(500)', 'image text', 'link text', 'sort_order integer DEFAULT 0', 'status integer DEFAULT 1', 'created_at timestamptz DEFAULT now()'],
  cms_egp: ['id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY', 'type varchar(20)', 'project_id varchar(100)', 'name text', 'description text', 'link text', 'pub_date date', 'guid varchar(255)', 'created_at timestamptz DEFAULT now()', 'updated_at timestamptz DEFAULT now()'],
  ebook_category: ['id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY', 'name varchar(255) NOT NULL', 'status integer DEFAULT 1'],
  ebook: ['id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY', 'ebook_category_id bigint', 'name varchar(500)', 'description text', 'cover_image text', 'file_path text', 'status integer DEFAULT 1', 'created_at timestamptz DEFAULT now()'],
  menu_group: ['id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY', 'name varchar(255) NOT NULL', 'status integer DEFAULT 1'],
  menu: ['id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY', 'menu_group_id bigint', 'parent_id bigint', 'name varchar(255)', 'url text', 'sort_order integer DEFAULT 0', 'status integer DEFAULT 1'],
};

function collectTables(pages: unknown): string[] {
  const names = new Set<string>(['users']);
  const visit = (node: Node) => {
    const source = node.props?.dataSource as { table?: unknown; tables?: unknown } | undefined;
    if (typeof source?.table === 'string') names.add(source.table);
    if (Array.isArray(source?.tables)) source.tables.forEach((name) => { if (typeof name === 'string') names.add(name); });
    node.children?.forEach(visit);
  };
  if (Array.isArray(pages)) pages.forEach((page) => { const tree = (page as { componentTree?: Node[] }).componentTree; tree?.forEach(visit); });
  return [...names].filter((name) => /^[a-z_][a-z0-9_]*$/.test(name)).sort();
}

export async function publishTenantStructure(platformId: string) {
  const source = await getCoreDb().query<{ studio_pages: unknown }>('SELECT studio_pages FROM public.platforms WHERE id=$1', [platformId]);
  if (!source.rowCount) throw new Error('Platform not found');
  const tables = collectTables(source.rows[0].studio_pages);
  const definition = tables.map((name) => ({ name, columns: standardColumns[name] || ['id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY', 'data jsonb NOT NULL DEFAULT \'{}\'::jsonb', 'created_at timestamptz DEFAULT now()', 'updated_at timestamptz DEFAULT now()'] }));
  const revision = createHash('sha256').update(JSON.stringify(definition)).digest('hex').slice(0, 12);
  const { pool, database } = await getTenantDb(platformId);
  const client = await pool.connect();
  try {
    await client.query('BEGIN');
    for (const table of definition) await client.query(`CREATE TABLE IF NOT EXISTS public."${table.name}" (${table.columns.join(', ')})`);
    await client.query(`CREATE TABLE IF NOT EXISTS sys.structure_revisions (revision varchar(64) PRIMARY KEY, definition jsonb NOT NULL, published_at timestamptz NOT NULL DEFAULT now())`);
    await client.query(`CREATE TABLE IF NOT EXISTS sys.design_configs (scope varchar(30) NOT NULL, config_key varchar(120) NOT NULL, config_value jsonb NOT NULL, version integer NOT NULL, source_path text, synced_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(scope,config_key))`);
    const configs = await getCoreDb().query<{ scope: string; config_key: string; config_value: unknown; version: number; source_path: string | null }>(`SELECT scope,config_key,config_value,version,source_path FROM public.platform_design_configs WHERE platform_id=$1 AND enabled=true`, [platformId]);
    for (const config of configs.rows) await client.query(`INSERT INTO sys.design_configs(scope,config_key,config_value,version,source_path) VALUES($1,$2,$3::jsonb,$4,$5) ON CONFLICT(scope,config_key) DO UPDATE SET config_value=excluded.config_value,version=excluded.version,source_path=excluded.source_path,synced_at=now()`, [config.scope,config.config_key,JSON.stringify(config.config_value),config.version,config.source_path]);
    await client.query(`INSERT INTO sys.structure_revisions(revision,definition) VALUES($1,$2::jsonb) ON CONFLICT(revision) DO NOTHING`, [revision, JSON.stringify(definition)]);
    await client.query('COMMIT');
    return { database, revision, tables };
  } catch (error) { await client.query('ROLLBACK'); throw error; } finally { client.release(); }
}
