import { createHash } from 'node:crypto';
import { getCoreDb } from './coreDb';
import { getTenantDb } from './tenantDb';

type Node = { props?: Record<string, unknown>; children?: Node[] };

const DEFAULT_COLUMNS = [
  'id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY',
  "data jsonb NOT NULL DEFAULT '{}'::jsonb",
  'created_at timestamptz DEFAULT now()',
  'updated_at timestamptz DEFAULT now()',
];

const standardColumns: Record<string, string[]> = {
  users: ['id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY', 'email varchar(255) UNIQUE', 'full_name varchar(255)', 'role varchar(80)', 'status integer DEFAULT 1', 'created_at timestamptz DEFAULT now()', 'updated_at timestamptz DEFAULT now()'],
  auth_users: ['id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY', 'email varchar(255) UNIQUE NOT NULL', 'password_hash text NOT NULL', 'display_name varchar(255)', 'is_active boolean NOT NULL DEFAULT true', 'role_id bigint', 'created_at timestamptz DEFAULT now()', 'updated_at timestamptz DEFAULT now()'],
  auth_roles: ['id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY', 'name varchar(120) UNIQUE NOT NULL', 'description text'],
  auth_permissions: ['id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY', 'code varchar(180) UNIQUE NOT NULL', 'name varchar(255) NOT NULL', 'description text'],
  auth_role_permissions: ['role_id bigint NOT NULL REFERENCES auth_roles(id) ON DELETE CASCADE', 'permission_id bigint NOT NULL REFERENCES auth_permissions(id) ON DELETE CASCADE', 'PRIMARY KEY(role_id,permission_id)'],
  cms_file_category: ['id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY', 'name varchar(255) NOT NULL'],
  cms_file: ['id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY', 'cms_file_category_id bigint', 'name varchar(500)', 'file_path text', 'status integer DEFAULT 1', 'created_at timestamptz DEFAULT now()', 'updated_at timestamptz DEFAULT now()'],
  cms_post: ['id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY', 'cms_category_id bigint', 'name varchar(500)', 'description text', 'image text', 'status integer DEFAULT 1', 'publish_at timestamptz', 'created_at timestamptz DEFAULT now()', 'updated_at timestamptz DEFAULT now()'],
  cms_page: ['id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY', 'name varchar(500)', 'description text', 'slug varchar(255)', 'status integer DEFAULT 1', 'created_at timestamptz DEFAULT now()', 'updated_at timestamptz DEFAULT now()'],
  cms_menu: ['id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY', 'parent_id bigint', 'menu_name varchar(255)', 'url text', 'icon varchar(255)', 'position varchar(40)', 'sort_order integer DEFAULT 0', 'status integer DEFAULT 1', 'created_at timestamptz DEFAULT now()', 'updated_at timestamptz DEFAULT now()'],
  cms_slide: ['id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY', 'name varchar(500)', 'image text', 'link text', 'sort_order integer DEFAULT 0', 'status integer DEFAULT 1', 'created_at timestamptz DEFAULT now()'],
  cms_egp: ['id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY', 'type varchar(20)', 'project_id varchar(100)', 'name text', 'description text', 'link text', 'pub_date date', 'guid varchar(255)', 'created_at timestamptz DEFAULT now()', 'updated_at timestamptz DEFAULT now()'],
  ebook_category: ['id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY', 'name varchar(255) NOT NULL', 'status integer DEFAULT 1'],
  ebook: ['id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY', 'ebook_category_id bigint', 'name varchar(500)', 'description text', 'cover_image text', 'file_path text', 'status integer DEFAULT 1', 'created_at timestamptz DEFAULT now()'],
  menu_group: ['id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY', 'name varchar(255) NOT NULL', 'status integer DEFAULT 1'],
  menu: ['id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY', 'menu_group_id bigint', 'parent_id bigint', 'name varchar(255)', 'url text', 'sort_order integer DEFAULT 0', 'status integer DEFAULT 1'],
};

function collectTables(pages: unknown, collections: unknown): string[] {
  const names = new Set<string>(['users']);
  const visit = (node: Node) => {
    const source = node.props?.dataSource as { table?: unknown; tables?: unknown } | undefined;
    if (typeof source?.table === 'string') names.add(source.table);
    if (Array.isArray(source?.tables)) source.tables.forEach((name) => { if (typeof name === 'string') names.add(name); });
    node.children?.forEach(visit);
  };
  if (Array.isArray(pages)) pages.forEach((page) => { const tree = (page as { componentTree?: Node[] }).componentTree; tree?.forEach(visit); });
  if (Array.isArray(collections)) {
    collections.forEach((item) => {
      const table = (item as { table?: unknown }).table;
      if (typeof table === 'string') names.add(table);
    });
  }
  // auth_role_permissions references the other auth tables, so it is created last.
  if (names.has('auth_users') || names.has('auth_roles') || names.has('auth_permissions')) {
    names.add('auth_role_permissions');
  }
  return [...names]
    .filter((name) => /^[a-z_][a-z0-9_]*$/.test(name))
    .sort((a, b) => {
      if (a === 'auth_role_permissions') return 1;
      if (b === 'auth_role_permissions') return -1;
      return a.localeCompare(b);
    });
}

export interface PublishResult {
  database: string;
  revision: string;
  tables: string[];
}

/**
 * Creates the tables referenced by a platform's component trees inside that
 * platform's own tenant database, then syncs design configs into `sys`.
 * The published definition is recorded so a revision can be traced later.
 */
export async function publishTenantStructure(platformId: string): Promise<PublishResult> {
  const source = await getCoreDb().query<{ studio_pages: unknown; studio_collections: unknown }>(
    'SELECT studio_pages, studio_collections FROM public.platforms WHERE id = $1',
    [platformId],
  );
  if (!source.rowCount) throw new Error('Platform not found');

  const tables = collectTables(source.rows[0].studio_pages, source.rows[0].studio_collections);
  const definition = tables.map((name) => ({ name, columns: standardColumns[name] || DEFAULT_COLUMNS }));
  const revision = createHash('sha256').update(JSON.stringify(definition)).digest('hex').slice(0, 12);

  const { pool, database } = await getTenantDb(platformId);
  const client = await pool.connect();
  try {
    await client.query('BEGIN');
    await client.query('CREATE EXTENSION IF NOT EXISTS pgcrypto');
    for (const table of definition) {
      await client.query(`CREATE TABLE IF NOT EXISTS public."${table.name}" (${table.columns.join(', ')})`);
    }

    const configs = await getCoreDb().query<{
      scope: string; config_key: string; config_value: unknown; version: number; source_path: string | null;
    }>(
      `SELECT scope, config_key, config_value, version, source_path
       FROM public.platform_design_configs WHERE platform_id = $1 AND enabled = true`,
      [platformId],
    );

    for (const config of configs.rows) {
      await client.query(
        `INSERT INTO sys.design_configs (scope, config_key, config_value, version, source_path)
         VALUES ($1, $2, $3::jsonb, $4, $5)
         ON CONFLICT (scope, config_key) DO UPDATE SET
           config_value = excluded.config_value, version = excluded.version,
           source_path = excluded.source_path, synced_at = now()`,
        [config.scope, config.config_key, JSON.stringify(config.config_value), config.version, config.source_path],
      );
    }

    await client.query(
      `INSERT INTO sys.structure_revisions (revision, definition) VALUES ($1, $2::jsonb)
       ON CONFLICT (revision) DO NOTHING`,
      [revision, JSON.stringify(definition)],
    );
    await client.query('COMMIT');
    return { database, revision, tables };
  } catch (error) {
    await client.query('ROLLBACK');
    throw error;
  } finally {
    client.release();
  }
}

/** Tables a platform has actually published — the allow-list for record CRUD. */
export async function publishedTables(platformId: string): Promise<Set<string>> {
  const { pool } = await getTenantDb(platformId);
  const result = await pool.query<{ table_name: string }>(
    `SELECT table_name FROM information_schema.tables
     WHERE table_schema = 'public' AND table_type = 'BASE TABLE'`,
  );
  return new Set(result.rows.map((row) => row.table_name));
}
