import type { ComponentNode } from '@/types';

export interface StudioCollectionDefinition {
  id: string; moduleId: string; name: string; table: string; primaryKey: string[];
  operations: Array<'list' | 'get' | 'create' | 'update' | 'delete'>;
  relations?: Array<{ field: string; collectionId: string; displayField: string }>;
  scope: 'project'; tenantTarget: boolean;
  standardFlows: {
    create: { trigger: 'create'; target: 'FormComponent'; formId: string; params: { mode: 'insert' } };
    edit: { trigger: 'edit'; source: 'DataTableComponent'; target: 'FormComponent'; formId: string; rowIdField: string; params: { mode: 'update' } };
    view: { trigger: 'view'; source: 'DataTableComponent'; target: 'DynamicHtmlComponent'; componentId: string; rowIdField: string; params: { mode: 'preview' } };
  };
  components: Array<{ id: string; type: 'DataTableComponent' | 'FormComponent' | 'ListComponent' | 'GalleryComponent' | 'DynamicHtmlComponent'; label: string; recommended?: boolean; componentTree: ComponentNode[]; variantComponentTrees?: Record<string, ComponentNode[]> }>;
}

export interface StudioFormDefinition {
  id: string; moduleId: string; name: string; permission: string; collectionId: string;
  source: { routeCreate: string; routeUpdate: string; formView: string; model: string };
  componentTree: ComponentNode[]; version: number;
  modeComponentTrees?: Partial<Record<'insert' | 'update' | 'readOnly', ComponentNode[]>>;
}

type Field = { name: string; label: string; type?: string; required?: boolean; collectionId?: string; displayField?: string };
const ops: StudioCollectionDefinition['operations'] = ['list', 'get', 'create', 'update', 'delete'];
const QUERY_BY_TABLE: Record<string, { statement: string; source: string; parameters: Array<{ name: string; type: string; value: unknown }> }> = {
  cms_post: { source: 'backend/modules/cms/models/PostSearch.php', statement: `SELECT p.id, p.cms_category_id, c.name AS category_name, p.name, p.hit, p.status, p.publish_at, p.files, p.gallery, p.tags, p.created_by, u.name AS created_by_name\nFROM cms_post p\nLEFT JOIN cms_category c ON c.id = p.cms_category_id\nLEFT JOIN "user" u ON u.id = p.created_by\nWHERE (:cms_category_id IS NULL OR p.cms_category_id = :cms_category_id)\n  AND (:status IS NULL OR p.status = :status)\n  AND (:search IS NULL OR p.name ILIKE '%' || :search || '%' OR p.description ILIKE '%' || :search || '%' OR p.tags ILIKE '%' || :search || '%')\nORDER BY p.id DESC\nLIMIT :limit OFFSET :offset`, parameters: [{ name: 'cms_category_id', type: 'number', value: null }, { name: 'status', type: 'number', value: null }, { name: 'search', type: 'string', value: null }, { name: 'limit', type: 'number', value: 20 }, { name: 'offset', type: 'number', value: 0 }] },
  cms_category: { source: 'backend/modules/cms/models/CategorySearch.php', statement: `SELECT id, name, created_at, updated_at, created_by, updated_by\nFROM cms_category\nWHERE (:id IS NULL OR id = :id) AND (:search IS NULL OR name ILIKE '%' || :search || '%')\nORDER BY id ASC\nLIMIT :limit OFFSET :offset`, parameters: [{ name: 'id', type: 'number', value: null }, { name: 'search', type: 'string', value: null }, { name: 'limit', type: 'number', value: 20 }, { name: 'offset', type: 'number', value: 0 }] },
  cms_page: { source: 'backend/modules/cms/models/PageSearch.php', statement: `SELECT id, name, description, hit, created_at, updated_at, created_by, updated_by\nFROM cms_page\nWHERE (:search IS NULL OR name ILIKE '%' || :search || '%' OR description ILIKE '%' || :search || '%')\nORDER BY id DESC\nLIMIT :limit OFFSET :offset`, parameters: [{ name: 'search', type: 'string', value: null }, { name: 'limit', type: 'number', value: 20 }, { name: 'offset', type: 'number', value: 0 }] },
  cms_personnel: { source: 'backend/modules/cms/models/PersonnelSearch.php', statement: `SELECT p.id, p.cms_personnel_group_id, g.name AS group_name, p.parent_id, p.name, p.position, p.photo, p.tier, p.sort_order\nFROM cms_personnel p\nLEFT JOIN cms_personnel_group g ON g.id = p.cms_personnel_group_id\nWHERE (:group_id IS NULL OR p.cms_personnel_group_id = :group_id) AND (:search IS NULL OR p.name ILIKE '%' || :search || '%' OR p.position ILIKE '%' || :search || '%')\nORDER BY p.id DESC\nLIMIT :limit OFFSET :offset`, parameters: [{ name: 'group_id', type: 'number', value: null }, { name: 'search', type: 'string', value: null }, { name: 'limit', type: 'number', value: 20 }, { name: 'offset', type: 'number', value: 0 }] },
  cms_personnel_group: { source: 'backend/modules/cms/models/PersonnelGroupSearch.php', statement: `SELECT id, name FROM cms_personnel_group WHERE (:search IS NULL OR name ILIKE '%' || :search || '%') ORDER BY id ASC LIMIT :limit OFFSET :offset`, parameters: [{ name: 'search', type: 'string', value: null }, { name: 'limit', type: 'number', value: 20 }, { name: 'offset', type: 'number', value: 0 }] },
  cms_slide: { source: 'backend/modules/cms/models/SlideSearch.php', statement: `SELECT id, name, description, slide, status, sort_order, always_show, show_from, show_to\nFROM cms_slide\nWHERE (:status IS NULL OR status = :status) AND (:search IS NULL OR name ILIKE '%' || :search || '%' OR description ILIKE '%' || :search || '%')\nORDER BY sort_order ASC, id DESC\nLIMIT :limit OFFSET :offset`, parameters: [{ name: 'status', type: 'number', value: null }, { name: 'search', type: 'string', value: null }, { name: 'limit', type: 'number', value: 20 }, { name: 'offset', type: 'number', value: 0 }] },
  banner_slide: { source: 'backend/modules/cms/models/BannerSlideSearch.php', statement: `SELECT id, title AS name, description, image AS image_url, sort_order, status, always_show, show_from, show_to\nFROM banner_slide\nWHERE (:status IS NULL OR status = :status) AND (:search IS NULL OR title ILIKE '%' || :search || '%' OR description ILIKE '%' || :search || '%')\nORDER BY sort_order ASC, id ASC\nLIMIT :limit OFFSET :offset`, parameters: [{ name: 'status', type: 'number', value: null }, { name: 'search', type: 'string', value: null }, { name: 'limit', type: 'number', value: 20 }, { name: 'offset', type: 'number', value: 0 }] },
  cms_file: { source: 'backend/modules/cms/models/CmsFileSearch.php', statement: `SELECT f.id, f.cms_file_category_id, c.name AS category_name, f.name, f.files, f.created_at, f.updated_at\nFROM cms_file f LEFT JOIN cms_file_category c ON c.id = f.cms_file_category_id\nWHERE (:category_id IS NULL OR f.cms_file_category_id = :category_id) AND (:search IS NULL OR f.name ILIKE '%' || :search || '%' OR f.files ILIKE '%' || :search || '%')\nORDER BY f.id DESC LIMIT :limit OFFSET :offset`, parameters: [{ name: 'category_id', type: 'number', value: null }, { name: 'search', type: 'string', value: null }, { name: 'limit', type: 'number', value: 20 }, { name: 'offset', type: 'number', value: 0 }] },
  cms_file_category: { source: 'backend/modules/cms/models/CmsFileCategorySearch.php', statement: `SELECT id, name FROM cms_file_category WHERE (:search IS NULL OR name ILIKE '%' || :search || '%') ORDER BY id ASC LIMIT :limit OFFSET :offset`, parameters: [{ name: 'search', type: 'string', value: null }, { name: 'limit', type: 'number', value: 20 }, { name: 'offset', type: 'number', value: 0 }] },
  menu: { source: 'backend/modules/cms/models/MenuSearch.php', statement: `SELECT m.id, m.menu_group_id, g.name AS group_name, m.name, m.is_head, m.content_type, m.link, m.disply, m.menu_id, parent.name AS parent_name, m.status\nFROM menu m\nLEFT JOIN menu_group g ON g.id = m.menu_group_id\nLEFT JOIN menu parent ON parent.id = m.menu_id\nWHERE (:group_id IS NULL OR m.menu_group_id = :group_id) AND (:search IS NULL OR m.name ILIKE '%' || :search || '%' OR m.link ILIKE '%' || :search || '%')\nORDER BY m.id ASC LIMIT :limit OFFSET :offset`, parameters: [{ name: 'group_id', type: 'number', value: null }, { name: 'search', type: 'string', value: null }, { name: 'limit', type: 'number', value: 20 }, { name: 'offset', type: 'number', value: 0 }] },
  menu_group: { source: 'backend/modules/cms/models/MenuGroupSearch.php', statement: `SELECT id, name, status FROM menu_group WHERE (:search IS NULL OR name ILIKE '%' || :search || '%') ORDER BY id ASC LIMIT :limit OFFSET :offset`, parameters: [{ name: 'search', type: 'string', value: null }, { name: 'limit', type: 'number', value: 20 }, { name: 'offset', type: 'number', value: 0 }] },
  ebook: { source: 'backend/modules/ebook/models/EbookSearch.php', statement: `SELECT e.id, e.ebook_category_id, c.name AS category_name, e.name, e.description, e.cover, e.ebook_file, e.created_at\nFROM ebook e LEFT JOIN ebook_category c ON c.id = e.ebook_category_id\nWHERE (:category_id IS NULL OR e.ebook_category_id = :category_id) AND (:search IS NULL OR e.name ILIKE '%' || :search || '%')\nORDER BY e.id DESC LIMIT :limit OFFSET :offset`, parameters: [{ name: 'category_id', type: 'number', value: null }, { name: 'search', type: 'string', value: null }, { name: 'limit', type: 'number', value: 20 }, { name: 'offset', type: 'number', value: 0 }] },
  ebook_category: { source: 'backend/modules/ebook/models/EbookCategorySearch.php', statement: `SELECT id, name FROM ebook_category WHERE (:search IS NULL OR name ILIKE '%' || :search || '%') ORDER BY id ASC LIMIT :limit OFFSET :offset`, parameters: [{ name: 'search', type: 'string', value: null }, { name: 'limit', type: 'number', value: 20 }, { name: 'offset', type: 'number', value: 0 }] },
  cms_homepage_highlight: { source: 'backend/modules/cms/controllers/HomepageHighlightController.php', statement: `SELECT config_key AS id, config_value, updated_at FROM platform_design_configs WHERE config_key = 'homepage_highlight'`, parameters: [{ name: 'limit', type: 'number', value: 1 }, { name: 'offset', type: 'number', value: 0 }] },
  cms_contact_channel: { source: 'backend/modules/cms/controllers/ContactChannelController.php', statement: `SELECT config_key AS id, config_value, updated_at FROM platform_design_configs WHERE config_key = 'contact_channel'`, parameters: [{ name: 'limit', type: 'number', value: 1 }, { name: 'offset', type: 'number', value: 0 }] },
  cms_grayscale: { source: 'backend/modules/cms/controllers/GrayscaleController.php', statement: `SELECT config_key AS id, config_value, updated_at FROM platform_design_configs WHERE config_key = 'frontend_display'`, parameters: [{ name: 'limit', type: 'number', value: 1 }, { name: 'offset', type: 'number', value: 0 }] },
  complaint: { source: 'backend/modules/cms/models/ComplaintSearch.php', statement: `SELECT id, title, name, id_card, tel, email, topic, process, status, proceed, remark, created_at FROM complaint WHERE (:status IS NULL OR status = :status) AND (:search IS NULL OR name ILIKE '%' || :search || '%' OR topic ILIKE '%' || :search || '%') ORDER BY id DESC LIMIT :limit OFFSET :offset`, parameters: [{ name: 'status', type: 'number', value: null }, { name: 'search', type: 'string', value: null }, { name: 'limit', type: 'number', value: 20 }, { name: 'offset', type: 'number', value: 0 }] },
  corrupt: { source: 'backend/modules/cms/models/CorruptSearch.php', statement: `SELECT id, title, name, id_card, tel, email, topic, process, status, proceed, remark, created_at FROM corrupt WHERE (:status IS NULL OR status = :status) AND (:search IS NULL OR name ILIKE '%' || :search || '%' OR topic ILIKE '%' || :search || '%') ORDER BY id DESC LIMIT :limit OFFSET :offset`, parameters: [{ name: 'status', type: 'number', value: null }, { name: 'search', type: 'string', value: null }, { name: 'limit', type: 'number', value: 20 }, { name: 'offset', type: 'number', value: 0 }] },
  personalreport: { source: 'backend/modules/cms/models/PersonalreportSearch.php', statement: `SELECT id, title, name, tel, email, topic, belong_to, because, purpose, status, created_at FROM personalreport WHERE (:status IS NULL OR status = :status) AND (:search IS NULL OR name ILIKE '%' || :search || '%' OR topic ILIKE '%' || :search || '%') ORDER BY id DESC LIMIT :limit OFFSET :offset`, parameters: [{ name: 'status', type: 'number', value: null }, { name: 'search', type: 'string', value: null }, { name: 'limit', type: 'number', value: 20 }, { name: 'offset', type: 'number', value: 0 }] },
  generalhelp: { source: 'backend/modules/cms/models/GeneralhelpSearch.php', statement: `SELECT id, title, name, id_card, tel, email, topic, description, status, created_at FROM generalhelp WHERE (:status IS NULL OR status = :status) AND (:search IS NULL OR name ILIKE '%' || :search || '%' OR topic ILIKE '%' || :search || '%') ORDER BY id DESC LIMIT :limit OFFSET :offset`, parameters: [{ name: 'status', type: 'number', value: null }, { name: 'search', type: 'string', value: null }, { name: 'limit', type: 'number', value: 20 }, { name: 'offset', type: 'number', value: 0 }] },
  oldage: { source: 'backend/modules/cms/models/OldageSearch.php', statement: `SELECT id, title, name, id_card, bdate, nation, tel, status, created_at FROM oldage WHERE (:status IS NULL OR status = :status) AND (:search IS NULL OR name ILIKE '%' || :search || '%' OR id_card ILIKE '%' || :search || '%') ORDER BY id DESC LIMIT :limit OFFSET :offset`, parameters: [{ name: 'status', type: 'number', value: null }, { name: 'search', type: 'string', value: null }, { name: 'limit', type: 'number', value: 20 }, { name: 'offset', type: 'number', value: 0 }] },
  usewater: { source: 'backend/modules/cms/models/UsewaterSearch.php', statement: `SELECT id, title, name, id_card, tel, address, status, created_at FROM usewater WHERE (:status IS NULL OR status = :status) AND (:search IS NULL OR name ILIKE '%' || :search || '%') ORDER BY id DESC LIMIT :limit OFFSET :offset`, parameters: [{ name: 'status', type: 'number', value: null }, { name: 'search', type: 'string', value: null }, { name: 'limit', type: 'number', value: 20 }, { name: 'offset', type: 'number', value: 0 }] },
  electric: { source: 'backend/modules/cms/models/ElectricSearch.php', statement: `SELECT id, title, name, tel, lamp_id, map, description, status, created_at FROM electric WHERE (:status IS NULL OR status = :status) AND (:search IS NULL OR name ILIKE '%' || :search || '%' OR lamp_id ILIKE '%' || :search || '%') ORDER BY id DESC LIMIT :limit OFFSET :offset`, parameters: [{ name: 'status', type: 'number', value: null }, { name: 'search', type: 'string', value: null }, { name: 'limit', type: 'number', value: 20 }, { name: 'offset', type: 'number', value: 0 }] },
  getbin: { source: 'backend/modules/cms/models/GetbinSearch.php', statement: `SELECT id, title, name, id_card, tel, map, status, created_at FROM getbin WHERE (:status IS NULL OR status = :status) AND (:search IS NULL OR name ILIKE '%' || :search || '%') ORDER BY id DESC LIMIT :limit OFFSET :offset`, parameters: [{ name: 'status', type: 'number', value: null }, { name: 'search', type: 'string', value: null }, { name: 'limit', type: 'number', value: 20 }, { name: 'offset', type: 'number', value: 0 }] },
  handicapped: { source: 'backend/modules/cms/models/HandicappedSearch.php', statement: `SELECT id, title, name, id_card, tel, status, created_at FROM handicapped WHERE (:status IS NULL OR status = :status) AND (:search IS NULL OR name ILIKE '%' || :search || '%' OR id_card ILIKE '%' || :search || '%') ORDER BY id DESC LIMIT :limit OFFSET :offset`, parameters: [{ name: 'status', type: 'number', value: null }, { name: 'search', type: 'string', value: null }, { name: 'limit', type: 'number', value: 20 }, { name: 'offset', type: 'number', value: 0 }] },
  onlinequeue: { source: 'backend/modules/cms/models/OnlinequeueSearch.php', statement: `SELECT id, title, name, id_card, tel, qdate, qtime, topic, status, created_at FROM onlinequeue WHERE (:status IS NULL OR status = :status) AND (:search IS NULL OR name ILIKE '%' || :search || '%') ORDER BY id DESC LIMIT :limit OFFSET :offset`, parameters: [{ name: 'status', type: 'number', value: null }, { name: 'search', type: 'string', value: null }, { name: 'limit', type: 'number', value: 20 }, { name: 'offset', type: 'number', value: 0 }] },
  cms_tag: { source: 'backend/modules/cms/models/CmsPostTag.php', statement: `SELECT id, name FROM cms_tag WHERE (:search IS NULL OR name ILIKE '%' || :search || '%') ORDER BY id ASC LIMIT :limit OFFSET :offset`, parameters: [{ name: 'search', type: 'string', value: null }, { name: 'limit', type: 'number', value: 20 }, { name: 'offset', type: 'number', value: 0 }] },
  report_ticket: { source: 'backend/modules/smartreport/models/ReportTicketSearch.php', statement: `SELECT t.id, t.category_id, c.name AS category_name, t.urgency_id, u.name AS urgency_name, t.status_id, s.name AS status_name, t.reporter_name, t.reporter_phone, t.title, t.created_at, t.completed_at\nFROM report_ticket t\nLEFT JOIN report_category c ON c.id = t.category_id\nLEFT JOIN report_urgency u ON u.id = t.urgency_id\nLEFT JOIN report_status s ON s.id = t.status_id\nWHERE (:status_id IS NULL OR t.status_id = :status_id) AND (:category_id IS NULL OR t.category_id = :category_id) AND (:search IS NULL OR t.title ILIKE '%' || :search || '%' OR t.reporter_name ILIKE '%' || :search || '%')\nORDER BY t.id DESC LIMIT :limit OFFSET :offset`, parameters: [{ name: 'status_id', type: 'number', value: null }, { name: 'category_id', type: 'number', value: null }, { name: 'search', type: 'string', value: null }, { name: 'limit', type: 'number', value: 20 }, { name: 'offset', type: 'number', value: 0 }] },
  report_category: { source: 'backend/modules/smartreport/models/ReportCategorySearch.php', statement: `SELECT id, name, icon, description, status FROM report_category WHERE (:search IS NULL OR name ILIKE '%' || :search || '%') ORDER BY id ASC LIMIT :limit OFFSET :offset`, parameters: [{ name: 'search', type: 'string', value: null }, { name: 'limit', type: 'number', value: 20 }, { name: 'offset', type: 'number', value: 0 }] },
  report_urgency: { source: 'backend/modules/smartreport/models/ReportUrgencySearch.php', statement: `SELECT id, name, color_code, level_value FROM report_urgency ORDER BY level_value ASC LIMIT :limit OFFSET :offset`, parameters: [{ name: 'limit', type: 'number', value: 20 }, { name: 'offset', type: 'number', value: 0 }] },
  report_status: { source: 'backend/modules/smartreport/models/ReportStatusSearch.php', statement: `SELECT id, name, color_code, is_closed FROM report_status ORDER BY id ASC LIMIT :limit OFFSET :offset`, parameters: [{ name: 'limit', type: 'number', value: 20 }, { name: 'offset', type: 'number', value: 0 }] },
  booking_service: { source: 'backend/modules/booking/models/BookingServiceSearch.php', statement: `SELECT id, name, status, description FROM booking_service WHERE (:search IS NULL OR name ILIKE '%' || :search || '%') ORDER BY id ASC LIMIT :limit OFFSET :offset`, parameters: [{ name: 'search', type: 'string', value: null }, { name: 'limit', type: 'number', value: 20 }, { name: 'offset', type: 'number', value: 0 }] },
  booking_queue: { source: 'backend/modules/booking/models/BookingQueueSearch.php', statement: `SELECT q.id, q.queue_number, q.service_id, s.name AS service_name, q.booking_date, q.booking_time, q.status, q.remark, q.created_at\nFROM booking_queue q\nLEFT JOIN booking_service s ON s.id = q.service_id\nWHERE (:service_id IS NULL OR q.service_id = :service_id) AND (:status IS NULL OR q.status = :status) AND (:search IS NULL OR q.queue_number ILIKE '%' || :search || '%')\nORDER BY q.id DESC LIMIT :limit OFFSET :offset`, parameters: [{ name: 'service_id', type: 'number', value: null }, { name: 'status', type: 'number', value: null }, { name: 'search', type: 'string', value: null }, { name: 'limit', type: 'number', value: 20 }, { name: 'offset', type: 'number', value: 0 }] },
  forum_thread: { source: 'backend/modules/forum/models/ForumThreadSearch.php', statement: `SELECT t.id, t.forum_category_id, c.name AS category_name, t.name, t.thread_by, t.thread_tel, t.status, t.created_at\nFROM forum_thread t LEFT JOIN forum_category c ON c.id = t.forum_category_id\nWHERE (:category_id IS NULL OR t.forum_category_id = :category_id) AND (:status IS NULL OR t.status = :status) AND (:search IS NULL OR t.name ILIKE '%' || :search || '%' OR t.thread_by ILIKE '%' || :search || '%')\nORDER BY t.id DESC LIMIT :limit OFFSET :offset`, parameters: [{ name: 'category_id', type: 'number', value: null }, { name: 'status', type: 'number', value: null }, { name: 'search', type: 'string', value: null }, { name: 'limit', type: 'number', value: 20 }, { name: 'offset', type: 'number', value: 0 }] },
  forum_category: { source: 'backend/modules/forum/models/ForumCategorySearch.php', statement: `SELECT id, name, description FROM forum_category WHERE (:search IS NULL OR name ILIKE '%' || :search || '%') ORDER BY id ASC LIMIT :limit OFFSET :offset`, parameters: [{ name: 'search', type: 'string', value: null }, { name: 'limit', type: 'number', value: 20 }, { name: 'offset', type: 'number', value: 0 }] },
  forum_comment: { source: 'backend/modules/forum/models/ForumCommentSearch.php', statement: `SELECT c.id, c.forum_thread_id, t.name AS thread_title, c.forum_comment, c.comment_by, c.status, c.created_at\nFROM forum_comment c LEFT JOIN forum_thread t ON t.id = c.forum_thread_id\nWHERE (:thread_id IS NULL OR c.forum_thread_id = :thread_id) AND (:search IS NULL OR c.forum_comment ILIKE '%' || :search || '%' OR c.comment_by ILIKE '%' || :search || '%')\nORDER BY c.id DESC LIMIT :limit OFFSET :offset`, parameters: [{ name: 'thread_id', type: 'number', value: null }, { name: 'search', type: 'string', value: null }, { name: 'limit', type: 'number', value: 20 }, { name: 'offset', type: 'number', value: 0 }] },
  cms_menu: { source: 'backend/modules/administrator/models/CmsMenuSearch.php', statement: `SELECT id, menu_name, position, parent_id, url, icon, sort_order FROM cms_menu WHERE (:position IS NULL OR position = :position) AND (:search IS NULL OR menu_name ILIKE '%' || :search || '%') ORDER BY sort_order ASC, id ASC LIMIT :limit OFFSET :offset`, parameters: [{ name: 'position', type: 'string', value: null }, { name: 'search', type: 'string', value: null }, { name: 'limit', type: 'number', value: 20 }, { name: 'offset', type: 'number', value: 0 }] },
  user: { source: 'backend/modules/administrator/models/UserSearch.php', statement: `SELECT id, username, name, realname, email, tel_x, mobile, status, role, last_login, created_at FROM "user" WHERE (:status IS NULL OR status = :status) AND (:search IS NULL OR username ILIKE '%' || :search || '%' OR name ILIKE '%' || :search || '%' OR email ILIKE '%' || :search || '%') ORDER BY id DESC LIMIT :limit OFFSET :offset`, parameters: [{ name: 'status', type: 'number', value: null }, { name: 'search', type: 'string', value: null }, { name: 'limit', type: 'number', value: 20 }, { name: 'offset', type: 'number', value: 0 }] },
  auth_assignment: { source: 'vendor/yiisoft/yii2-rbac/models/Assignment.php', statement: `SELECT item_name AS role_name, user_id, created_at FROM auth_assignment ORDER BY created_at DESC LIMIT :limit OFFSET :offset`, parameters: [{ name: 'limit', type: 'number', value: 20 }, { name: 'offset', type: 'number', value: 0 }] },
  auth_item: { source: 'vendor/yiisoft/yii2-rbac/models/Item.php', statement: `SELECT name, type, description, rule_name, data, created_at, updated_at FROM auth_item WHERE (:type IS NULL OR type = :type) AND (:search IS NULL OR name ILIKE '%' || :search || '%' OR description ILIKE '%' || :search || '%') ORDER BY name ASC LIMIT :limit OFFSET :offset`, parameters: [{ name: 'type', type: 'number', value: null }, { name: 'search', type: 'string', value: null }, { name: 'limit', type: 'number', value: 20 }, { name: 'offset', type: 'number', value: 0 }] },
};
const YANG_POST_DYNAMIC_STYLE = {
  name: 'yang-new/ka-post-grid',
  sourceFile: 'backend/themes/yang-new/assets/css/kare-admin.css',
  sourceSelectors: ['.ka-card', '.ka-card .card-header', '.table-ka thead th', '.table-ka td', '.table-ka tbody tr:hover', '.table-action-group', '.btn-view', '.btn-edit', '.btn-delete', '.btn-ka-primary'],
  tokens: { primary: '#2e5d1c', primaryDark: '#1b3810', border: '#dfe8c8', surface: '#ffffff', text: '#1c2b14', radius: '14px', transition: '0.2s ease' },
  card: { border: '1px solid #dfe8c8', borderRadius: '14px', boxShadow: '0 2px 8px rgba(26,54,14,0.08)', background: '#ffffff' },
  header: { padding: '0.9rem 1.25rem', borderBottom: '1px solid #dfe8c8', background: 'transparent' },
  title: { color: '#1c2b14', fontWeight: 600 },
  createButton: { background: '#2e5d1c', color: '#ffffff', border: 'none', borderRadius: '6px', padding: '0.45rem 1.25rem', fontSize: '0.875rem', fontWeight: 500 },
  tableHead: { background: '#2e5d1c', color: '#ffffff', border: 'none', padding: '0.75rem 1rem', fontSize: '0.85rem', fontWeight: 500 },
  tableCell: { verticalAlign: 'middle', padding: '0.6rem 1rem', fontSize: '0.875rem' },
  filterInput: { borderColor: '#dfe8c8', borderRadius: '8px', fontSize: '0.875rem' },
  rowHoverBackground: 'rgba(46,93,28,0.04)',
  actionButtons: {
    view: { width: '28px', height: '28px', borderRadius: '6px', border: 'none', background: 'rgba(46,93,28,0.1)', color: '#2e5d1c' },
    edit: { width: '28px', height: '28px', borderRadius: '6px', border: 'none', background: 'rgba(212,175,55,0.15)', color: '#c99700' },
    delete: { width: '28px', height: '28px', borderRadius: '6px', border: 'none', background: 'rgba(220,53,69,0.1)', color: '#dc3545' },
  },
};
const collection = (id: string, moduleId: string, name: string, table: string, relations?: StudioCollectionDefinition['relations'], preferred: 'DataTableComponent' | 'ListComponent' | 'GalleryComponent' = 'DataTableComponent', options?: { formId?: string; queryStatement?: string; queryParameters?: Array<{ name: string; type: string; value: unknown }> }): StudioCollectionDefinition => {
  const formId = options?.formId || `${id.replace(/\.collection$/, '')}.form`;
  const baseQuery = QUERY_BY_TABLE[table] || { statement: `SELECT * FROM ${table} LIMIT :limit OFFSET :offset`, source: 'auto-generated', parameters: [{ name: 'limit', type: 'number', value: 20 }, { name: 'offset', type: 'number', value: 0 }] };
  const query = { ...baseQuery, statement: options?.queryStatement || baseQuery.statement, parameters: options?.queryParameters || baseQuery.parameters };
  const dataSource = { kind: 'query', statement: query.statement, parameters: query.parameters, source: { framework: 'yii2-active-record', file: query.source, translatedFor: 'postgresql' } };
  const sample = table === 'cms_post'
    ? [
        { id: 1, category_name: 'ข่าวสารประชาสัมพันธ์', name: 'ประกาศรายชื่อผู้มีสิทธิเข้ารับการสรรหาและเลือกสรรเป็นพนักงานจ้าง', hit: 29, publish_at: '2026-08-21', created_by_name: 'อบต.ยาง' },
        { id: 2, category_name: 'สรุปผลการดำเนินการจัดซื้อจัดจ้าง', name: 'สรุปผลการจัดซื้อจัดจ้าง ประจำเดือนกรกฎาคม พ.ศ. 2569', hit: 6, publish_at: '2026-08-04', created_by_name: 'อบต.ยาง' },
        { id: 3, category_name: 'ข่าวสารประชาสัมพันธ์', name: 'ประกาศรับสมัครบุคคลเพื่อการสรรหาและการเลือกสรรเป็นพนักงานจ้าง', hit: 39, publish_at: '2026-07-27', created_by_name: 'อบต.ยาง' },
      ]
    : [1, 2, 3].map((sampleId) => ({ id: sampleId, name: `${name} ตัวอย่าง ${sampleId}`, description: `Sample record for ${table}`, imageUrl: `https://picsum.photos/seed/${table}-${sampleId}/480/320`, category: name }));
  const tableProps = table === 'cms_post' ? {
    titleIcon: '▣', createLabel: 'เพิ่มข่าวสาร/เนื้อหา', searchable: false, columnFilters: true, actionLabel: 'จัดการ',
    columns: [
      { key: 'id', label: '#', sortable: true, width: 50 },
      { key: 'category_name', label: 'หมวดหมู่', sortable: true, filter: true, width: 175 },
      { key: 'name', label: 'ชื่อเรื่อง', sortable: true, filter: true },
      { key: 'hit', label: 'ยอดเข้าชม', sortable: true, filter: true, format: 'number', align: 'center', width: 120 },
      { key: 'publish_at', label: 'วันที่เผยแพร่', sortable: true, format: 'date', align: 'center', width: 150 },
      { key: 'created_by_name', label: 'ผู้สร้าง', filter: true, width: 140 },
    ],
    rowActions: [{ id: 'view', label: 'ดูข้อมูล', variant: 'view' }, { id: 'edit', label: 'แก้ไข', variant: 'edit' }, { id: 'delete', label: 'ลบ', variant: 'delete' }],
    dynamicStyle: YANG_POST_DYNAMIC_STYLE,
  } : { createLabel: `เพิ่ม${name}`, columns: [{ key: 'id', label: 'ID', sortable: true }, { key: 'name', label: 'ชื่อรายการ', sortable: true }], searchable: true, rowActions: [{ id: 'view', label: 'ดูข้อมูล', variant: 'view' }, { id: 'edit', label: 'แก้ไข', variant: 'edit' }, { id: 'delete', label: 'ลบ', variant: 'delete' }] };
  const components: StudioCollectionDefinition['components'] = [
    { id: `${id}.datatable`, type: 'DataTableComponent', label: 'Data Table', recommended: preferred === 'DataTableComponent', componentTree: [{ id: `${id}_datatable`, type: 'DataTableComponent', props: { title: name, collectionId: id, dataSource, ...tableProps, data: sample, pageSize: 10 } }] },
    { id: `${id}.form`, type: 'FormComponent', label: 'Form', componentTree: [{ id: `${id}_form_ref`, type: 'FormComponent', props: { title: name, collectionId: id, formId, fields: [], submitText: 'บันทึกข้อมูล' } }] },
    { id: `${id}.list`, type: 'ListComponent', label: 'List', recommended: preferred === 'ListComponent', componentTree: [{ id: `${id}_list`, type: 'ListComponent', props: { title: name, collectionId: id, dataSource, primaryField: 'name', secondaryField: 'description', items: sample } }] },
    { id: `${id}.gallery`, type: 'GalleryComponent', label: 'Gallery', recommended: preferred === 'GalleryComponent', componentTree: [{ id: `${id}_gallery`, type: 'GalleryComponent', props: { title: name, collectionId: id, dataSource, imageField: 'imageUrl', titleField: 'name', items: sample, columns: 3 } }] },
    { id: `${id}.view-detail`, type: 'DynamicHtmlComponent', label: 'ViewDetail', componentTree: [{ id: `${id}_view_detail`, type: 'DynamicHtmlComponent', props: { title: `${name} Detail`, collectionId: id, componentRole: 'CollectionViewDetail', surfaces: ['preview', 'frontend'], dataBinding: { source: 'selectedRow', primaryKey: 'id' }, content: `<article class="card border-0 shadow-sm"><header class="card-header bg-white p-4"><div class="small text-muted">${name}</div><h2 class="mb-0">{{name}}</h2></header><section class="card-body p-4"><dl class="row mb-0"><dt class="col-sm-3">ID</dt><dd class="col-sm-9">{{id}}</dd><dt class="col-sm-3">รายละเอียด</dt><dd class="col-sm-9">{{description}}</dd></dl></section></article>` } }] },
    { id: `${id}.document`, type: 'DynamicHtmlComponent', label: 'Document', componentTree: [{ id: `${id}_document`, type: 'DynamicHtmlComponent', props: { title: `${name} Document`, collectionId: id, componentRole: 'CollectionDocument', designSurface: 'canvas', outputFormats: ['canvas', 'pdf'], page: { size: 'A4', orientation: 'portrait', margin: '20mm' }, dataBinding: { source: 'selectedRow', primaryKey: 'id' }, content: `<main style="width:210mm;min-height:297mm;padding:20mm;background:#fff;color:#111"><h1>${name}</h1><hr/><p><strong>เลขที่:</strong> {{id}}</p><p><strong>ชื่อ:</strong> {{name}}</p><div>{{description}}</div></main>` } }] },
  ];
  return { id, moduleId, name, table, primaryKey: ['id'], operations: ops, relations, scope: 'project', tenantTarget: true, standardFlows: {
    create: { trigger: 'create', target: 'FormComponent', formId, params: { mode: 'insert' } },
    edit: { trigger: 'edit', source: 'DataTableComponent', target: 'FormComponent', formId, rowIdField: 'id', params: { mode: 'update' } },
    view: { trigger: 'view', source: 'DataTableComponent', target: 'DynamicHtmlComponent', componentId: `${id}.view-detail`, rowIdField: 'id', params: { mode: 'preview' } },
  }, components };
};
const form = (id: string, moduleId: string, name: string, controller: string, model: string, fields: Field[], collectionId = `${id.replace(/\.form$/, '')}.collection`, sourceModule = moduleId): StudioFormDefinition => {
  const now = Date.now();
  return { id, moduleId, name, permission: moduleId, collectionId, version: 1,
    source: { routeCreate: `/${sourceModule}/${controller}/create`, routeUpdate: `/${sourceModule}/${controller}/update?id=:id`, formView: `backend/modules/${sourceModule}/views/${controller}/_form.php`, model: `common/models/${model}.php` },
    componentTree: [
      { id: `${id}_layout_${now}`, type: 'DynamicHtmlComponent', props: { __sectionId: 'form-header', __sectionName: '01. Form Header', componentRole: 'GeneratedYiiFormLayout', content: `<section class="p-3 border-bottom"><h1>${name}</h1><p class="text-muted mb-0">Create / Update form generated from YII source</p></section>` } },
      { id: `${id}_fields_${now}`, type: 'FormComponent', props: { __sectionId: 'form-fields', __sectionName: '02. Form Fields', title: name, collectionId, mode: ['create', 'update'], fields, submitText: 'บันทึกข้อมูล' } },
    ] };
};

export const CMS_COLLECTION_SEEDS: StudioCollectionDefinition[] = [
  collection('cms.category.collection', 'cms', 'หมวดหมู่ข่าวสาร', 'cms_category', undefined, 'ListComponent'),
  collection('cms.post.collection', 'cms', 'ข่าวสาร/เนื้อหา', 'cms_post', [{ field: 'cms_category_id', collectionId: 'cms.category.collection', displayField: 'name' }, { field: 'created_by', collectionId: 'administrator.user.collection', displayField: 'name' }]),
  collection('cms.page.collection', 'cms', 'หน้าเว็บไซต์', 'cms_page'),
  collection('cms.personnel-group.collection', 'cms', 'กลุ่มบุคลากร', 'cms_personnel_group', undefined, 'ListComponent'),
  collection('cms.personnel.collection', 'cms', 'บุคลากร', 'cms_personnel', [{ field: 'cms_personnel_group_id', collectionId: 'cms.personnel-group.collection', displayField: 'name' }], 'GalleryComponent'),
  collection('cms.slide.collection', 'cms', 'ภาพสไลด์', 'cms_slide', undefined, 'GalleryComponent'), collection('cms.banner-slide.collection', 'cms', 'Banner Slideshow', 'banner_slide', undefined, 'GalleryComponent'),
  collection('cms.file-category.collection', 'cms', 'หมวดหมู่ไฟล์', 'cms_file_category', undefined, 'ListComponent'),
  collection('cms.file.collection', 'cms', 'ไฟล์ดาวน์โหลด', 'cms_file', [{ field: 'cms_file_category_id', collectionId: 'cms.file-category.collection', displayField: 'name' }]),
  collection('cms.menu-group.collection', 'cms', 'กลุ่มเมนูเว็บไซต์', 'menu_group', undefined, 'ListComponent'),
  collection('cms.menu.collection', 'cms', 'เมนูเว็บไซต์', 'menu', [{ field: 'menu_group_id', collectionId: 'cms.menu-group.collection', displayField: 'name' }, { field: 'menu_id', collectionId: 'cms.menu.collection', displayField: 'name' }], 'ListComponent'),
  collection('cms.ebook-category.collection', 'cms', 'หมวดหมู่ E-Book', 'ebook_category', undefined, 'ListComponent'),
  collection('cms.ebook.collection', 'cms', 'หนังสือ E-Book', 'ebook', [{ field: 'ebook_category_id', collectionId: 'cms.ebook-category.collection', displayField: 'name' }], 'GalleryComponent'),
  collection('cms.homepage-highlight.collection', 'cms', 'รูปนายกและปลัด', 'cms_homepage_highlight'),
  collection('cms.contact-channel.collection', 'cms', 'ช่องทางติดต่อ', 'cms_contact_channel'),
  collection('cms.grayscale.collection', 'cms', 'โหมดสีเทาหน้าเว็บ', 'cms_grayscale'),
  collection('cms.complaint.collection', 'cms', 'ร้องเรียนร้องทุกข์', 'complaint'),
  collection('cms.corrupt.collection', 'cms', 'ร้องเรียนทุจริต', 'corrupt'),
  collection('cms.personalreport.collection', 'cms', 'ร้องเรียนบุคลากร', 'personalreport'),
  collection('cms.generalhelp.collection', 'cms', 'ขอความช่วยเหลือทั่วไป', 'generalhelp'),
  collection('cms.oldage.collection', 'cms', 'เบี้ยยังชีพผู้สูงอายุ', 'oldage'),
  collection('cms.usewater.collection', 'cms', 'ขอน้ำเพื่อบริโภค', 'usewater'),
  collection('cms.electric.collection', 'cms', 'ซ่อมไฟฟ้า/สาธารณะ', 'electric'),
  collection('cms.getbin.collection', 'cms', 'ขอรับบริการถังขยะ', 'getbin'),
  collection('cms.handicapped.collection', 'cms', 'ทะเบียนเบี้ยพิการ', 'handicapped'),
  collection('cms.onlinequeue.collection', 'cms', 'คิวออนไลน์', 'onlinequeue'),
  collection('cms.tag.collection', 'cms', 'แท็กเนื้อหา', 'cms_tag', undefined, 'ListComponent'),
];

export const CMS_FORM_SEEDS: StudioFormDefinition[] = [
  form('cms.post.form', 'cms', 'ข่าวสาร/เนื้อหา', 'post', 'CmsPost', [{ name: 'name', label: 'เรื่อง', required: true }, { name: 'cms_category_id', label: 'หมวดหมู่', type: 'collection-select', collectionId: 'cms.category.collection', displayField: 'name', required: true }, { name: 'publish_at', label: 'วันที่เผยแพร่', type: 'datetime', required: true }, { name: 'status', label: 'สถานะ', type: 'switch' }, { name: 'tags', label: 'แท็ก', type: 'tags' }, { name: 'description', label: 'รายละเอียด', type: 'html-editor', required: true }, { name: 'files', label: 'ไฟล์ประกอบ', type: 'file' }, { name: 'gallery', label: 'อัลบั้ม', type: 'multi-file' }]),
  form('cms.category.form', 'cms', 'หมวดหมู่ข่าวสาร', 'category', 'CmsCategory', [{ name: 'name', label: 'ชื่อหมวดหมู่', required: true }]),
  form('cms.page.form', 'cms', 'หน้าเว็บไซต์', 'page', 'CmsPage', [{ name: 'name', label: 'ชื่อหน้า', required: true }, { name: 'description', label: 'เนื้อหา', type: 'html-editor', required: true }]),
  form('cms.personnel.form', 'cms', 'บุคลากร', 'personnel', 'CmsPersonnel', [{ name: 'name', label: 'ชื่อ', required: true }, { name: 'position', label: 'ตำแหน่ง' }, { name: 'photo', label: 'รูปภาพ', type: 'file' }, { name: 'cms_personnel_group_id', label: 'กลุ่มบุคลากร', type: 'collection-select', collectionId: 'cms.personnel-group.collection', displayField: 'name' }, { name: 'tier', label: 'ระดับ', type: 'number' }, { name: 'sort_order', label: 'ลำดับ', type: 'number' }]),
  form('cms.personnel-group.form', 'cms', 'กลุ่มบุคลากร', 'personnel-group', 'CmsPersonnelGroup', [{ name: 'name', label: 'ชื่อกลุ่ม', required: true }]),
  form('cms.slide.form', 'cms', 'ภาพสไลด์', 'slide', 'CmsSlide', [{ name: 'name', label: 'ชื่อ', required: true }, { name: 'description', label: 'รายละเอียด', type: 'textarea' }, { name: 'slide', label: 'รูปสไลด์', type: 'file' }, { name: 'sort_order', label: 'ลำดับ', type: 'number' }, { name: 'show_from', label: 'แสดงตั้งแต่', type: 'datetime' }, { name: 'show_to', label: 'แสดงถึง', type: 'datetime' }]),
  form('cms.banner-slide.form', 'cms', 'Banner Slideshow', 'banner-slide', 'BannerSlide', [{ name: 'title', label: 'หัวข้อ', required: true }, { name: 'description', label: 'รายละเอียด', type: 'textarea' }, { name: 'image', label: 'รูป Banner', type: 'file' }, { name: 'sort_order', label: 'ลำดับ', type: 'number' }, { name: 'show_from', label: 'แสดงตั้งแต่', type: 'datetime' }, { name: 'show_to', label: 'แสดงถึง', type: 'datetime' }]),
  form('cms.file.form', 'cms', 'ไฟล์ดาวน์โหลด', 'file', 'CmsFile', [{ name: 'cms_file_category_id', label: 'หมวดหมู่', type: 'collection-select', collectionId: 'cms.file-category.collection', displayField: 'name' }, { name: 'name', label: 'ชื่อไฟล์', required: true }, { name: 'files', label: 'ไฟล์', type: 'file', required: true }]),
  form('cms.file-category.form', 'cms', 'หมวดหมู่ไฟล์', 'file-category', 'CmsFileCategory', [{ name: 'name', label: 'ชื่อหมวดหมู่', required: true }]),
  form('cms.menu.form', 'cms', 'เมนูเว็บไซต์', 'menu', 'Menu', [{ name: 'menu_group_id', label: 'กลุ่มเมนู', type: 'collection-select', collectionId: 'cms.menu-group.collection', displayField: 'name' }, { name: 'name', label: 'ชื่อเมนู', required: true }, { name: 'content_type', label: 'ประเภทเนื้อหา' }, { name: 'link', label: 'ลิงก์' }, { name: 'disply', label: 'รูปแบบแสดงผล' }, { name: 'menu_id', label: 'เมนูแม่', type: 'collection-select', collectionId: 'cms.menu.collection', displayField: 'name' }, { name: 'status', label: 'สถานะ', type: 'switch' }]),
  form('cms.menu-group.form', 'cms', 'กลุ่มเมนูเว็บไซต์', 'menu-group', 'MenuGroup', [{ name: 'name', label: 'ชื่อกลุ่ม', required: true }, { name: 'status', label: 'สถานะ', type: 'switch' }]),
  form('cms.ebook.form', 'cms', 'หนังสือ E-Book', 'ebook', 'Ebook', [{ name: 'ebook_category_id', label: 'หมวดหมู่', type: 'collection-select', collectionId: 'cms.ebook-category.collection', displayField: 'name', required: true }, { name: 'name', label: 'ชื่อหนังสือ', required: true }, { name: 'description', label: 'คำอธิบาย', type: 'textarea' }, { name: 'cover', label: 'ภาพหน้าปก', type: 'file' }, { name: 'ebook_file', label: 'ไฟล์ PDF', type: 'file', required: true }], 'cms.ebook.collection', 'ebook'),
  form('cms.ebook-category.form', 'cms', 'หมวดหมู่ E-Book', 'ebook-category', 'EbookCategory', [{ name: 'name', label: 'ชื่อหมวดหมู่', required: true }], 'cms.ebook-category.collection', 'ebook'),
  form('cms.homepage-highlight.form', 'cms', 'รูปนายกและปลัด', 'homepage-highlight', 'HomepageHighlight', [{ name: 'left_image', label: 'รูปนายก', type: 'file' }, { name: 'right_image', label: 'รูปปลัด', type: 'file' }, { name: 'left_visible', label: 'แสดงรูปนายก', type: 'switch' }, { name: 'right_visible', label: 'แสดงรูปปลัด', type: 'switch' }]),
  form('cms.contact-channel.form', 'cms', 'ช่องทางติดต่อ', 'contact-channel', 'ContactChannel', [{ name: 'phone_text', label: 'เบอร์โทรศัพท์' }, { name: 'email_text', label: 'อีเมล' }, { name: 'facebook_url', label: 'Facebook Page' }, { name: 'messenger_url', label: 'Messenger' }, { name: 'google_map_url', label: 'Google Map URL' }]),
  form('cms.grayscale.form', 'cms', 'โหมดสีเทาหน้าเว็บ', 'grayscale', 'Grayscale', [{ name: 'grayscale_enabled', label: 'เปิดโหมดสีเทา', type: 'switch' }, { name: 'grayscale_percent', label: 'เปอร์เซ็นต์สีเทา (0-100)', type: 'number' }, { name: 'corner_ribbon_enabled', label: 'แสดงริบบิ้นไว้อาลัย', type: 'switch' }, { name: 'corner_ribbon_side', label: 'ตำแหน่งริบบิ้น (left/right)' }]),
  form('cms.complaint.form', 'cms', 'ร้องเรียนร้องทุกข์', 'compliant', 'Complaint', [{ name: 'title', label: 'คำนำหน้า', required: true }, { name: 'name', label: 'ชื่อ-นามสกุล', required: true }, { name: 'id_card', label: 'เลขบัตรประชาชน', required: true }, { name: 'tel', label: 'เบอร์โทรศัพท์', required: true }, { name: 'email', label: 'อีเมล' }, { name: 'topic', label: 'เรื่องร้องเรียน', required: true }, { name: 'description', label: 'รายละเอียด', type: 'textarea' }, { name: 'process', label: 'การดำเนินการที่ต้องการ', required: true }, { name: 'files', label: 'หลักฐานแนบ', type: 'file' }, { name: 'status', label: 'สถานะรับเรื่อง', type: 'number' }, { name: 'proceed', label: 'ผลการดำเนินการ', type: 'textarea' }, { name: 'remark', label: 'หมายเหตุ', type: 'textarea' }]),
  form('cms.corrupt.form', 'cms', 'ร้องเรียนทุจริต', 'corrupt', 'Corrupt', [{ name: 'title', label: 'คำนำหน้า', required: true }, { name: 'name', label: 'ชื่อ-นามสกุล', required: true }, { name: 'id_card', label: 'เลขบัตรประชาชน', required: true }, { name: 'tel', label: 'เบอร์โทรศัพท์', required: true }, { name: 'topic', label: 'เรื่องร้องเรียนทุจริต', required: true }, { name: 'description', label: 'รายละเอียด', type: 'textarea' }, { name: 'files', label: 'หลักฐานแนบ', type: 'file' }, { name: 'status', label: 'สถานะรับเรื่อง', type: 'number' }]),
  form('cms.personalreport.form', 'cms', 'ร้องเรียนบุคลากร', 'personalreport', 'Personalreport', [{ name: 'title', label: 'คำนำหน้า', required: true }, { name: 'name', label: 'ชื่อผู้แจ้ง', required: true }, { name: 'tel', label: 'เบอร์โทรศัพท์', required: true }, { name: 'belong_to', label: 'บุคลากร/หน่วยงานที่ถูกกล่าวหา', required: true }, { name: 'topic', label: 'เรื่องที่ร้องเรียน', required: true }, { name: 'because', label: 'สาเหตุ/พฤติกรรม', type: 'textarea' }, { name: 'purpose', label: 'ความประสงค์', type: 'textarea' }]),
  form('cms.generalhelp.form', 'cms', 'ขอความช่วยเหลือทั่วไป', 'generalhelp', 'Generalhelp', [{ name: 'title', label: 'คำนำหน้า', required: true }, { name: 'name', label: 'ชื่อ-นามสกุล', required: true }, { name: 'id_card', label: 'เลขบัตรประชาชน', required: true }, { name: 'tel', label: 'เบอร์โทรศัพท์', required: true }, { name: 'topic', label: 'เรื่องขอความช่วยเหลือ', required: true }, { name: 'description', label: 'รายละเอียดความช่วยเหลือ', type: 'textarea' }]),
  form('cms.oldage.form', 'cms', 'เบี้ยยังชีพผู้สูงอายุ', 'oldage', 'Oldage', [{ name: 'title', label: 'คำนำหน้า', required: true }, { name: 'name', label: 'ชื่อ-นามสกุล', required: true }, { name: 'id_card', label: 'เลขบัตรประชาชน', required: true }, { name: 'bdate', label: 'วันเกิด', type: 'date', required: true }, { name: 'nation', label: 'สัญชาติ' }, { name: 'tel', label: 'เบอร์โทรศัพท์', required: true }]),
  form('cms.usewater.form', 'cms', 'ขอน้ำเพื่อบริโภค', 'usewater', 'Usewater', [{ name: 'title', label: 'คำนำหน้า', required: true }, { name: 'name', label: 'ชื่อ-นามสกุล', required: true }, { name: 'id_card', label: 'เลขบัตรประชาชน', required: true }, { name: 'address', label: 'ที่อยู่จัดส่งน้ำ', type: 'textarea', required: true }, { name: 'tel', label: 'เบอร์โทรศัพท์', required: true }]),
  form('cms.electric.form', 'cms', 'ซ่อมไฟฟ้า/สาธารณะ', 'electric', 'Electric', [{ name: 'title', label: 'คำนำหน้า', required: true }, { name: 'name', label: 'ชื่อผู้แจ้ง', required: true }, { name: 'tel', label: 'เบอร์โทรศัพท์', required: true }, { name: 'lamp_id', label: 'รหัสเสาไฟฟ้า/จุดชำรุด', required: true }, { name: 'map', label: 'พิกัดแผนที่' }, { name: 'description', label: 'อาการชำรุด', type: 'textarea' }]),
  form('cms.getbin.form', 'cms', 'ขอรับบริการถังขยะ', 'getbin', 'Getbin', [{ name: 'title', label: 'คำนำหน้า', required: true }, { name: 'name', label: 'ชื่อผู้ขอ', required: true }, { name: 'id_card', label: 'เลขบัตรประชาชน', required: true }, { name: 'tel', label: 'เบอร์โทรศัพท์', required: true }, { name: 'map', label: 'จุดวางถังขยะ' }]),
  form('cms.handicapped.form', 'cms', 'ทะเบียนเบี้ยพิการ', 'handicapped', 'Handicapped', [{ name: 'title', label: 'คำนำหน้า', required: true }, { name: 'name', label: 'ชื่อผู้พิการ', required: true }, { name: 'id_card', label: 'เลขบัตรประชาชน', required: true }, { name: 'tel', label: 'เบอร์โทรผู้ติดต่อ', required: true }]),
  form('cms.onlinequeue.form', 'cms', 'คิวออนไลน์', 'onlinequeue', 'Onlinequeue', [{ name: 'title', label: 'คำนำหน้า', required: true }, { name: 'name', label: 'ชื่อผู้จองคิว', required: true }, { name: 'id_card', label: 'เลขบัตรประชาชน', required: true }, { name: 'tel', label: 'เบอร์โทรศัพท์', required: true }, { name: 'qdate', label: 'วันที่นัดหมาย', type: 'date', required: true }, { name: 'qtime', label: 'เวลาที่นัดหมาย', required: true }, { name: 'topic', label: 'เรื่องที่มาติดต่อ', required: true }]),
  form('cms.tag.form', 'cms', 'แท็กเนื้อหา', 'tag', 'CmsPostTag', [{ name: 'name', label: 'ชื่อแท็ก', required: true }]),
];

export const SMARTREPORT_COLLECTION_SEEDS: StudioCollectionDefinition[] = [
  collection('smartreport.category.collection', 'smartreport', 'หมวดหมู่การแจ้งเหตุ', 'report_category', undefined, 'ListComponent'),
  collection('smartreport.urgency.collection', 'smartreport', 'ระดับความเร่งด่วน', 'report_urgency', undefined, 'ListComponent'),
  collection('smartreport.status.collection', 'smartreport', 'สถานะงานแจ้งเหตุ', 'report_status', undefined, 'ListComponent'),
  collection('smartreport.ticket.collection', 'smartreport', 'รายการรับแจ้งเหตุอัจฉริยะ', 'report_ticket', [
    { field: 'category_id', collectionId: 'smartreport.category.collection', displayField: 'name' },
    { field: 'urgency_id', collectionId: 'smartreport.urgency.collection', displayField: 'name' },
    { field: 'status_id', collectionId: 'smartreport.status.collection', displayField: 'name' },
  ], 'DataTableComponent', { formId: 'smartreport.ticket-workflow.form' }),
];

export const SMARTREPORT_FORM_SEEDS: StudioFormDefinition[] = [
  form('smartreport.category.form', 'smartreport', 'หมวดหมู่การแจ้งเหตุ', 'category', 'ReportCategory', [{ name: 'name', label: 'ชื่อหมวดหมู่', required: true }, { name: 'icon', label: 'ไอคอน' }, { name: 'description', label: 'รายละเอียด', type: 'textarea' }, { name: 'status', label: 'สถานะใช้งาน', type: 'switch' }]),
  form('smartreport.urgency.form', 'smartreport', 'ระดับความเร่งด่วน', 'urgency', 'ReportUrgency', [{ name: 'name', label: 'ชื่อระดับความเร่งด่วน', required: true }, { name: 'color_code', label: 'สีประจำระดับ (#HEX)', required: true }, { name: 'level_value', label: 'ระดับความสำคัญ (1-5)', type: 'number', required: true }]),
  form('smartreport.status.form', 'smartreport', 'สถานะงานแจ้งเหตุ', 'status', 'ReportStatus', [{ name: 'name', label: 'ชื่อสถานะงาน', required: true }, { name: 'color_code', label: 'สีประจำสถานะ (#HEX)' }, { name: 'is_closed', label: 'ถือเป็นเคสปิดงานแล้ว', type: 'switch' }]),
  form('smartreport.ticket-workflow.form', 'smartreport', 'รายการรับแจ้งเหตุอัจฉริยะ', 'ticket', 'ReportTicket', [
    { name: 'title', label: 'หัวข้อเรื่อง', required: true },
    { name: 'category_id', label: 'หมวดหมู่', type: 'collection-select', collectionId: 'smartreport.category.collection', displayField: 'name', required: true },
    { name: 'urgency_id', label: 'ความเร่งด่วน', type: 'collection-select', collectionId: 'smartreport.urgency.collection', displayField: 'name', required: true },
    { name: 'status_id', label: 'สถานะการดำเนินงาน', type: 'collection-select', collectionId: 'smartreport.status.collection', displayField: 'name', required: true },
    { name: 'reporter_name', label: 'ชื่อผู้แจ้ง' },
    { name: 'reporter_phone', label: 'เบอร์โทรศัพท์' },
    { name: 'description', label: 'รายละเอียดเหตุการณ์', type: 'textarea' },
    { name: 'address_detail', label: 'รายละเอียดพิกัด/สถานที่', type: 'textarea' },
  ], 'smartreport.ticket.collection'),
];

export const BOOKING_COLLECTION_SEEDS: StudioCollectionDefinition[] = [
  collection('booking.service.collection', 'booking', 'ประเภทบริการจองคิว', 'booking_service', undefined, 'ListComponent'),
  collection('booking.queue.collection', 'booking', 'รายการจองคิวออนไลน์', 'booking_queue', [{ field: 'service_id', collectionId: 'booking.service.collection', displayField: 'name' }, { field: 'user_id', collectionId: 'administrator.user.collection', displayField: 'name' }]),
];

export const BOOKING_FORM_SEEDS: StudioFormDefinition[] = [
  form('booking.service.form', 'booking', 'ประเภทบริการจองคิว', 'service', 'BookingService', [{ name: 'name', label: 'ชื่อบริการ', required: true }, { name: 'status', label: 'สถานะเปิดรับจอง', type: 'switch' }, { name: 'description', label: 'เงื่อนไขและรายละเอียด', type: 'textarea' }]),
  form('booking.queue.form', 'booking', 'รายการจองคิวออนไลน์', 'default', 'BookingQueue', [{ name: 'queue_number', label: 'เลขคิว', required: true }, { name: 'service_id', label: 'ประเภทบริการ', type: 'collection-select', collectionId: 'booking.service.collection', displayField: 'name', required: true }, { name: 'booking_date', label: 'วันที่นัดหมาย', type: 'date', required: true }, { name: 'booking_time', label: 'ช่วงเวลา', required: true }, { name: 'status', label: 'สถานะคิว', type: 'number' }, { name: 'remark', label: 'หมายเหตุเพิ่มเติม', type: 'textarea' }]),
];

export const FORUM_COLLECTION_SEEDS: StudioCollectionDefinition[] = [
  collection('forum.category.collection', 'forum', 'หมวดหมู่กระดานกระทู้', 'forum_category', undefined, 'ListComponent'),
  collection('forum.thread.collection', 'forum', 'หัวข้อกระทู้สนทนา', 'forum_thread', [{ field: 'forum_category_id', collectionId: 'forum.category.collection', displayField: 'name' }]),
  collection('forum.comment.collection', 'forum', 'ความคิดเห็น/ตอบกลับ', 'forum_comment', [{ field: 'forum_thread_id', collectionId: 'forum.thread.collection', displayField: 'name' }]),
];

export const FORUM_FORM_SEEDS: StudioFormDefinition[] = [
  form('forum.category.form', 'forum', 'หมวดหมู่กระดานกระทู้', 'category', 'ForumCategory', [{ name: 'name', label: 'ชื่อกระดานกระทู้', required: true }, { name: 'description', label: 'รายละเอียด', type: 'textarea' }]),
  form('forum.thread.form', 'forum', 'หัวข้อกระทู้สนทนา', 'thread', 'ForumThread', [{ name: 'forum_category_id', label: 'เลือกกระดานกระทู้', type: 'collection-select', collectionId: 'forum.category.collection', displayField: 'name', required: true }, { name: 'name', label: 'หัวข้อกระทู้', required: true }, { name: 'description', label: 'เนื้อหาข้อความ', type: 'html-editor', required: true }, { name: 'thread_by', label: 'ชื่อผู้โพสต์', required: true }, { name: 'thread_tel', label: 'เบอร์โทรศัพท์', required: true }, { name: 'thread_email', label: 'อีเมล' }, { name: 'thread_contact', label: 'ช่องทางติดต่อเพิ่มเติม' }, { name: 'status', label: 'สถานะการแสดงผล', type: 'switch' }]),
  form('forum.comment.form', 'forum', 'ความคิดเห็น/ตอบกลับ', 'comment', 'ForumComment', [{ name: 'forum_thread_id', label: 'กระทู้แม่', type: 'collection-select', collectionId: 'forum.thread.collection', displayField: 'name', required: true }, { name: 'forum_comment', label: 'ข้อความตอบกลับ', type: 'textarea', required: true }, { name: 'comment_by', label: 'ชื่อผู้ตอบ', required: true }, { name: 'status', label: 'สถานะ', type: 'switch' }]),
];

export const ADMINISTRATOR_COLLECTION_SEEDS: StudioCollectionDefinition[] = [
  collection('administrator.cms-menu.collection', 'administrator', 'เมนูระบบหลังบ้าน', 'cms_menu', [{ field: 'parent_id', collectionId: 'administrator.cms-menu.collection', displayField: 'menu_name' }], 'ListComponent'),
  collection('administrator.user.collection', 'administrator', 'ผู้ใช้งานระบบ', 'user'),
  collection('administrator.rbac-assignment.collection', 'administrator', 'การกำหนดสิทธิ์ผู้ใช้งาน', 'auth_assignment', [{ field: 'user_id', collectionId: 'administrator.user.collection', displayField: 'name' }], 'ListComponent'),
  collection('administrator.rbac-role.collection', 'administrator', 'บทบาทผู้ใช้ (Roles)', 'auth_item', undefined, 'ListComponent', { queryParameters: [{ name: 'type', type: 'number', value: 1 }, { name: 'search', type: 'string', value: null }, { name: 'limit', type: 'number', value: 20 }, { name: 'offset', type: 'number', value: 0 }] }),
  collection('administrator.rbac-permission.collection', 'administrator', 'สิทธิ์การเข้าถึง (Permissions)', 'auth_item', undefined, 'ListComponent', { queryParameters: [{ name: 'type', type: 'number', value: 2 }, { name: 'search', type: 'string', value: null }, { name: 'limit', type: 'number', value: 20 }, { name: 'offset', type: 'number', value: 0 }] }),
  collection('administrator.rbac-route.collection', 'administrator', 'เส้นทางระบบ (Routes)', 'auth_item', undefined, 'ListComponent', { queryStatement: `SELECT name, type, description, rule_name, data, created_at, updated_at FROM auth_item WHERE type = 2 AND name LIKE '/%' AND (:search IS NULL OR name ILIKE '%' || :search || '%') ORDER BY name ASC LIMIT :limit OFFSET :offset`, queryParameters: [{ name: 'search', type: 'string', value: null }, { name: 'limit', type: 'number', value: 20 }, { name: 'offset', type: 'number', value: 0 }] }),
];

export const ADMINISTRATOR_FORM_SEEDS: StudioFormDefinition[] = [
  form('administrator.cms-menu.form', 'administrator', 'เมนูระบบหลังบ้าน', 'cms-menu', 'CmsMenu', [{ name: 'menu_name', label: 'ชื่อเมนู', required: true }, { name: 'position', label: 'ตำแหน่ง (root)', required: true }, { name: 'parent_id', label: 'เมนูแม่', type: 'collection-select', collectionId: 'administrator.cms-menu.collection', displayField: 'menu_name' }, { name: 'url', label: 'URL Route', required: true }, { name: 'icon', label: 'ไอคอน' }, { name: 'sort_order', label: 'ลำดับ', type: 'number' }]),
  form('administrator.user.form', 'administrator', 'ผู้ใช้งานระบบ', 'user', 'User', [{ name: 'username', label: 'Username', required: true }, { name: 'name', label: 'ชื่อแสดงในระบบ', required: true }, { name: 'realname', label: 'ชื่อ-นามสกุลจริง' }, { name: 'email', label: 'อีเมล' }, { name: 'mobile', label: 'เบอร์โทรศัพท์มือถือ' }, { name: 'role', label: 'บทบาท (Role)' }, { name: 'status', label: 'สถานะบัญชี', type: 'number' }, { name: 'change_password', label: 'กำหนดรหัสผ่านใหม่', type: 'password' }]),
  form('administrator.rbac-assignment.form', 'administrator', 'การกำหนดสิทธิ์ผู้ใช้งาน', 'assignment', 'AuthAssignment', [{ name: 'user_id', label: 'ผู้ใช้', type: 'collection-select', collectionId: 'administrator.user.collection', displayField: 'name', required: true }, { name: 'role_name', label: 'บทบาทที่มอบหมาย', required: true }], 'administrator.rbac-assignment.collection', 'admin'),
  form('administrator.rbac-role.form', 'administrator', 'บทบาทผู้ใช้ (Roles)', 'role', 'AuthItem', [{ name: 'name', label: 'ชื่อบทบาท (Role Name)', required: true }, { name: 'description', label: 'คำอธิบายบทบาท', type: 'textarea' }], 'administrator.rbac-role.collection', 'admin'),
  form('administrator.rbac-permission.form', 'administrator', 'สิทธิ์การเข้าถึง (Permissions)', 'permission', 'AuthItem', [{ name: 'name', label: 'ชื่อสิทธิ์ (Permission Name)', required: true }, { name: 'description', label: 'คำอธิบายสิทธิ์', type: 'textarea' }], 'administrator.rbac-permission.collection', 'admin'),
  form('administrator.rbac-route.form', 'administrator', 'เส้นทางระบบ (Routes)', 'route', 'AuthItem', [{ name: 'name', label: 'Route Path (เช่น /cms/post/*)', required: true }, { name: 'description', label: 'คำอธิบาย route' }], 'administrator.rbac-route.collection', 'admin'),
  form('administrator.sms.form', 'administrator', 'ส่ง SMS', 'sms', 'Sms', [{ name: 'n', label: 'เบอร์โทรศัพท์ผู้รับ', required: true }, { name: 't', label: 'ข้อความ SMS', type: 'textarea', required: true }]),
];

export const ALL_BACKEND_COLLECTION_SEEDS: StudioCollectionDefinition[] = [
  ...CMS_COLLECTION_SEEDS,
  ...SMARTREPORT_COLLECTION_SEEDS,
  ...BOOKING_COLLECTION_SEEDS,
  ...FORUM_COLLECTION_SEEDS,
  ...ADMINISTRATOR_COLLECTION_SEEDS,
];

export const ALL_BACKEND_FORM_SEEDS: StudioFormDefinition[] = [
  ...CMS_FORM_SEEDS,
  ...SMARTREPORT_FORM_SEEDS,
  ...BOOKING_FORM_SEEDS,
  ...FORUM_FORM_SEEDS,
  ...ADMINISTRATOR_FORM_SEEDS,
];
