import type { ComponentType } from '@/types';

export type PropertyEditorKind = 'text' | 'textarea' | 'number' | 'boolean' | 'select' | 'json';
export interface SharedComponentPropertyField {
  key: string; label: string; editor: PropertyEditorKind; description?: string;
  options?: Array<{ label: string; value: string }>;
  placeholder?: string; defaultValue?: unknown;
}
export interface SharedComponentPropertyGroup { id: string; label: string; fields: SharedComponentPropertyField[] }
export interface SharedComponentPropertyDefinition { type: ComponentType; title: string; description: string; groups: SharedComponentPropertyGroup[] }

const field = (key: string, label: string, editor: PropertyEditorKind = 'text', extra: Partial<SharedComponentPropertyField> = {}): SharedComponentPropertyField => ({ key, label, editor, ...extra });
const content = (...fields: SharedComponentPropertyField[]): SharedComponentPropertyGroup => ({ id: 'content', label: 'Content & Display', fields });
const behavior = (...fields: SharedComponentPropertyField[]): SharedComponentPropertyGroup => ({ id: 'behavior', label: 'Behavior', fields });
const data = (...fields: SharedComponentPropertyField[]): SharedComponentPropertyGroup => ({ id: 'data', label: 'Data Configuration', fields });
const definition = (type: ComponentType, title: string, description: string, groups: SharedComponentPropertyGroup[]): SharedComponentPropertyDefinition => ({ type, title, description, groups });

export const SHARED_COMPONENT_PROPERTY_REGISTRY: Record<ComponentType, SharedComponentPropertyDefinition> = {
  SlideMenuComponent: definition('SlideMenuComponent', 'Slide Menu Properties', 'เมนูด้านข้างและโครงสร้างเมนูหลายระดับ', [content(field('title','Menu Title'), field('className','CSS Class')), behavior(field('defaultOpen','Open by default','boolean'))]),
  NavMenuComponent: definition('NavMenuComponent', 'Navigation Properties', 'เมนูนำทางแนวนอนและ branding', [content(field('brandName','Brand Name'), field('brandHref','Brand Link'), field('items','Navigation Items','json'))]),
  EditMenuComponent: definition('EditMenuComponent', 'Menu Editor Properties', 'ตัวแก้ไขลำดับและ hierarchy ของเมนู', [content(field('title','Title')), behavior(field('maxDepth','Maximum Depth','number'), field('allowDelete','Allow Delete','boolean'))]),
  FormComponent: definition('FormComponent', 'Form Properties', 'ฟอร์มรับข้อมูลและการ submit', [content(field('title','Title'), field('description','Description','textarea'), field('submitText','Submit Button Text')), data(field('formId','Form ID'), field('collectionId','Collection ID'), field('fields','Fields','json')), behavior(field('mode','Mode','select',{options:[{label:'Insert',value:'insert'},{label:'Update',value:'update'},{label:'Read only',value:'readOnly'}]}), field('operationBindings','Service operations (`service:bindingId:operation`)','json'))]),
  FieldInputComponent: definition('FieldInputComponent', 'Field Properties', 'ช่องรับข้อมูลหนึ่งฟิลด์', [content(field('name','Field Name'), field('label','Label'), field('placeholder','Placeholder'), field('type','Input Type')), behavior(field('required','Required','boolean'), field('disabled','Disabled','boolean'), field('readOnly','Read only','boolean'))]),
  TableDataComponent: definition('TableDataComponent', 'Table Properties', 'ตารางข้อมูลและ row actions', [content(field('title','Title'), field('titleIcon','Title Icon'), field('createLabel','Create Label')), data(field('columns','Columns','json'), field('pageSize','Page Size','number'), field('serviceBindingId','Data Service Binding'), field('serviceOperation','Data Service Operation')), behavior(field('searchable','Searchable','boolean'), field('columnFilters','Column Filters','boolean'), field('rowActions','Row Actions','json'))]),
  DataTableComponent: definition('DataTableComponent', 'Data Table Properties', 'ตารางข้อมูลขั้นสูง', [content(field('title','Title'), field('createLabel','Create Label')), data(field('columns','Columns','json'), field('pageSize','Page Size','number')), behavior(field('searchable','Searchable','boolean'), field('columnFilters','Column Filters','boolean'))]),
  PostListComponent: definition('PostListComponent', 'Post List Properties', 'รายการข่าว/ประกาศ พร้อมวันที่และสรุปย่อ', [content(field('title','Title'), field('subtitle','Subtitle'), field('emptyText','Empty Text'), field('moreHref','See-all Link'), field('moreLabel','See-all Label')), data(field('dataSource','Data Source','json'), field('items','Items','json')), behavior(field('variant','Variant','select',{options:[{label:'Card grid',value:'card'},{label:'Compact list',value:'compact'}]}), field('columns','Columns','number'))]),
  ListComponent: definition('ListComponent', 'List Properties', 'รายการข้อมูลแบบ primary/secondary field', [content(field('title','Title')), data(field('primaryField','Primary Field'), field('secondaryField','Secondary Field'), field('items','Fallback Items','json'))]),
  GalleryComponent: definition('GalleryComponent', 'Gallery Properties', 'แกลเลอรีรูปภาพหรือการ์ด', [content(field('title','Title')), data(field('imageField','Image Field'), field('titleField','Title Field'), field('items','Fallback Items','json')), behavior(field('columns','Columns','number'), field('showFilters','Show Filters','boolean'))]),
  FileManagerComponent: definition('FileManagerComponent', 'File Manager Properties', 'รายการและการจัดการไฟล์', [content(field('title','Title')), data(field('serviceBindingId','Storage Service Binding'), field('uploadOperation','Upload Operation')), behavior(field('allowUpload','Allow Upload','boolean'), field('allowDelete','Allow Delete','boolean'), field('accept','Accepted File Types'))]),
  FileManagerPopupComponent: definition('FileManagerPopupComponent', 'File Manager Popup Properties', 'Popup กลางสำหรับเลือก อัปโหลด และจัดการไฟล์', [content(field('title','Title'), field('rootPath','Root Path'), field('currentPath','Current Path')), data(field('pageSize','Page Size','number'), field('accept','Accepted File Types')), behavior(field('selectionMode','Selection Mode','select',{options:[{label:'Single',value:'single'},{label:'Multiple',value:'multiple'}]}), field('allowUpload','Allow Upload','boolean'), field('allowDirectoryMutation','Allow Directory Mutation','boolean'), field('allowDelete','Allow Delete','boolean'))]),
  DynamicHtmlComponent: definition('DynamicHtmlComponent', 'Dynamic HTML Properties', 'HTML content, runtime database content และ template binding', [content(field('title','Title'), field('content','Fallback HTML Content','textarea')), data(field('contentId','Runtime Content ID','text',{placeholder:'Page, Form, Collection หรือ Component ID'}), field('appSlug','Runtime App Slug'), field('refreshIntervalMs','Realtime Poll Interval (ms)','number'), field('dataBinding','Data Binding','json'))]),
  HtmlEditorComponent: definition('HtmlEditorComponent', 'HTML Editor Properties', 'Rich-text/HTML editor', [content(field('label','Label'), field('value','Initial HTML','textarea')), behavior(field('placeholder','Placeholder'), field('readOnly','Read only','boolean'))]),
  HtmlTemplateComponent: definition('HtmlTemplateComponent', 'HTML Template Properties', 'HTML Studio document wrapper', [content(field('title','Title')), behavior(field('className','CSS Class'))]),
  CardComponent: definition('CardComponent', 'Card Properties', 'การ์ดสรุปข้อมูล', [content(field('title','Title'), field('subtitle','Subtitle'), field('value','Value'), field('badge','Badge'), field('footerText','Footer Text')), behavior(field('variant','Variant','select',{options:['primary','success','warning','danger','info'].map(value=>({label:value,value}))}))]),
  ChartComponent: definition('ChartComponent', 'Chart Properties', 'กราฟและชุดข้อมูล', [content(field('title','Title')), data(field('chartType','Chart Type','select',{options:['bar','line','pie','doughnut'].map(value=>({label:value,value}))}), field('labels','Labels','json'), field('datasets','Datasets','json'))]),
  TabsContainerComponent: definition('TabsContainerComponent', 'Tabs Properties', 'Container แบบแท็บ', [content(field('tabs','Tabs','json')), behavior(field('activeTab','Active Tab'))]),
  AccordionComponent: definition('AccordionComponent', 'Accordion Properties', 'Container แบบ accordion', [content(field('items','Accordion Items','json')), behavior(field('allowMultiple','Allow Multiple','boolean'))]),
  ModalDialogComponent: definition('ModalDialogComponent', 'Modal Properties', 'หน้าต่าง dialog', [content(field('title','Title'), field('body','Body','textarea')), behavior(field('size','Size','select',{options:['sm','md','lg','xl'].map(value=>({label:value,value}))}), field('closeOnBackdrop','Close on Backdrop','boolean'))]),

  SiteTopbarComponent: definition('SiteTopbarComponent', 'Topbar Properties', 'แถบบนสุด: ช่องทางติดต่อ ปุ่มปรับขนาดตัวอักษร และโซเชียล', [content(field('phone','เบอร์โทรศัพท์'), field('email','อีเมล')), behavior(field('facebookUrl','Facebook URL'), field('youtubeUrl','YouTube URL'), field('lineUrl','LINE URL'))]),
  SiteHeaderComponent: definition('SiteHeaderComponent', 'Header Properties', 'ตราสัญลักษณ์ ชื่อหน่วยงาน และเมนูหลักหลายระดับ', [content(field('agencyName','ชื่อหน่วยงาน (ไทย)'), field('agencyNameEn','ชื่อหน่วยงาน (อังกฤษ)'), field('slogan','คำขวัญ'), field('emblemUrl','ไฟล์ตราสัญลักษณ์','text',{description:'ต้องเป็นไฟล์ทางการที่อัปโหลดเท่านั้น'})), data(field('items','เมนูหลัก','json'), field('homeHref','ลิงก์หน้าหลัก'))]),
  SiteSidebarMenuComponent: definition('SiteSidebarMenuComponent', 'Sidebar Menu Properties', 'เมนูหมวดหมู่ด้านข้าง รองรับเมนูย่อย', [content(field('title','หัวข้อเมนู')), data(field('items','รายการเมนู','json'))]),
  SiteFooterComponent: definition('SiteFooterComponent', 'Footer Properties', 'ที่อยู่ ช่องทางติดต่อ ลิงก์ และแผนที่', [content(field('agencyName','ชื่อหน่วยงาน'), field('address','ที่อยู่','textarea'), field('phone','โทรศัพท์'), field('fax','โทรสาร'), field('email','อีเมล'), field('officeHours','เวลาทำการ'), field('copyright','ข้อความลิขสิทธิ์')), data(field('groups','กลุ่มลิงก์','json'), field('mapEmbedUrl','ลิงก์แผนที่ (https เท่านั้น)'))]),
  HeroCarouselComponent: definition('HeroCarouselComponent', 'Hero Carousel Properties', 'แถบภาพเลื่อนหน้าแรก', [data(field('slides','ภาพและข้อความ','json')), behavior(field('interval','เวลาเลื่อน (วินาที)','number',{description:'0 = ไม่เลื่อนอัตโนมัติ'}))]),
  ServiceLinksComponent: definition('ServiceLinksComponent', 'Service Links Properties', 'ทางลัดบริการประชาชน', [content(field('title','หัวข้อ'), field('subtitle','คำอธิบาย')), data(field('items','รายการบริการ','json')), behavior(field('columns','จำนวนคอลัมน์','number'))]),
  StatCounterComponent: definition('StatCounterComponent', 'Statistics Properties', 'ตัวเลขสรุป เช่น จำนวนประชากร ผู้เข้าชม', [content(field('title','หัวข้อ')), data(field('items','รายการตัวเลข','json'))]),
  PeopleGridComponent: definition('PeopleGridComponent', 'People Grid Properties', 'ผู้บริหารและบุคลากร', [content(field('title','หัวข้อ'), field('subtitle','คำอธิบาย')), data(field('items','รายชื่อบุคลากร','json')), behavior(field('columns','จำนวนคอลัมน์','number'))]),
  FloatingDockComponent: definition('FloatingDockComponent', 'Floating Dock Properties', 'ปุ่มลอย: ติดต่อ โทร และกลับขึ้นด้านบน', [content(field('contactLabel','ข้อความปุ่มติดต่อ')), behavior(field('contactUrl','ลิงก์ติดต่อ'), field('phone','เบอร์โทรศัพท์'))]),
  SiteTickerComponent: definition('SiteTickerComponent', 'Ticker Properties', 'แถบข่าวเลื่อนใต้แบนเนอร์', [content(field('label','ข้อความนำ')), data(field('items','รายการข่าว','json'))]),
  SiteSearchComponent: definition('SiteSearchComponent', 'Search Properties', 'ช่องค้นหาทั้งเว็บไซต์', [content(field('placeholder','ข้อความในช่อง'), field('buttonLabel','ข้อความปุ่ม')), behavior(field('action','หน้าแสดงผลการค้นหา'))]),
  ExecutiveCardComponent: definition('ExecutiveCardComponent', 'Executive Properties', 'การ์ดผู้บริหารพร้อมป้ายชื่อ', [content(field('name','ชื่อ-นามสกุล'), field('position','ตำแหน่ง'), field('phone','เบอร์โทรศัพท์'), field('photo','ไฟล์ภาพถ่าย','text',{description:'ต้องเป็นภาพถ่ายจริงเท่านั้น'}))]),
  NoticeListComponent: definition('NoticeListComponent', 'Notice List Properties', 'รายการประกาศแบบมีวันที่', [content(field('title','หัวข้อ'), field('moreHref','ลิงก์ดูทั้งหมด'), field('moreLabel','ข้อความลิงก์'), field('emptyText','ข้อความเมื่อไม่มีข้อมูล')), data(field('dataSource','แหล่งข้อมูล','json'), field('items','รายการ','json'))]),
  PartnerStripComponent: definition('PartnerStripComponent', 'Partner Strip Properties', 'แถบลิงก์หน่วยงานที่เกี่ยวข้อง', [content(field('title','หัวข้อ')), data(field('items','รายการหน่วยงาน','json'))]),
  MediaFeatureComponent: definition('MediaFeatureComponent', 'Media Feature Properties', 'แบนเนอร์ภาพกว้างพร้อมปุ่ม เช่น วิดีโอแนะนำ แผนที่ แจ้งเตือน', [content(field('title','หัวข้อ'), field('subtitle','คำอธิบาย'), field('buttonLabel','ข้อความปุ่ม'), field('image','ไฟล์ภาพ'), field('alt','คำบรรยายภาพ')), behavior(field('href','ลิงก์ปลายทาง'), field('mark','เครื่องหมายทับภาพ','select',{options:[{label:'เล่นวิดีโอ',value:'play'},{label:'แผนที่',value:'map'},{label:'แจ้งเตือน',value:'alert'}]}), field('external','เปิดแท็บใหม่','boolean'))]),
  CookieConsentComponent: definition('CookieConsentComponent', 'Cookie Consent Properties', 'แถบแจ้งการใช้คุกกี้ด้านล่างจอ', [content(field('message','ข้อความ','textarea'), field('acceptLabel','ปุ่มยอมรับ'), field('declineLabel','ปุ่มใช้เฉพาะที่จำเป็น'), field('policyLabel','ข้อความลิงก์นโยบาย')), behavior(field('policyHref','ลิงก์นโยบายความเป็นส่วนตัว'))]),
  PagerComponent: definition('PagerComponent', 'Pager Properties', 'ตัวแบ่งหน้าของรายการ', [content(field('basePath','ที่อยู่หน้ารายการ'))]),
  LanguageSwitchComponent: definition('LanguageSwitchComponent', 'Language Properties', 'ปุ่มแปลภาษา โหลดตัวแปลเมื่อผู้ใช้เลือกเท่านั้น', [content(field('label','ข้อความปุ่ม')), data(field('languages','ภาษาที่ให้เลือก','json'))]),
  FloatingNoticeComponent: definition('FloatingNoticeComponent', 'Floating Notice Properties', 'การ์ดช่องทางร้องเรียนลอยด้านข้าง', [data(field('items','รายการช่องทาง','json'))]),
  EventCalendarComponent: definition('EventCalendarComponent', 'Calendar Properties', 'ปฏิทินกิจกรรมรายเดือน', [content(field('title','หัวข้อ'), field('subtitle','คำอธิบาย'), field('emptyText','ข้อความเมื่อไม่มีกิจกรรม')), data(field('dataSource','แหล่งข้อมูล','json'), field('items','รายการกิจกรรม','json'))]),
  VisitCounterComponent: definition('VisitCounterComponent', 'Visit Counter Properties', 'สถิติผู้เข้าชม นับด้วยระบบเอง ไม่ส่งข้อมูลออกภายนอก', [content(field('title','หัวข้อ')), behavior(field('appSlug','เว็บไซต์ที่นับ'))]),
  TabbedSectionComponent: definition('TabbedSectionComponent', 'Tabbed Section Properties', 'กลุ่มประกาศแบบแท็บ เช่น ประกาศจากระบบ e-GP', [content(field('title','หัวข้อ'), field('subtitle','คำอธิบาย')), data(field('tabs','แท็บและรายการ','json'))]),
  DocumentAccordionComponent: definition('DocumentAccordionComponent', 'Disclosure Properties', 'รายการเอกสารเปิดเผยแบบพับได้ เช่น ITA', [content(field('title','หัวข้อ'), field('subtitle','คำอธิบาย'), field('emptyText','ข้อความเมื่อไม่มีเอกสาร')), data(field('groups','กลุ่มและเอกสาร','json'))]),
  AlertChannelsComponent: definition('AlertChannelsComponent', 'Alert Channels Properties', 'ช่องทางแจ้งเหตุแยกตามประเภท', [content(field('title','หัวข้อ'), field('subtitle','คำอธิบาย'), field('ctaLabel','ข้อความปุ่มหลัก')), data(field('channels','ประเภทการแจ้งเหตุ','json')), behavior(field('ctaHref','ลิงก์ปุ่มหลัก'))]),
};

export const getSharedComponentPropertyDefinition = (type: ComponentType) => SHARED_COMPONENT_PROPERTY_REGISTRY[type];
