'use client';

import React, { useMemo, useState } from 'react';
import { ArrowDown, ArrowLeft, ArrowRight, ArrowUp, Eye, Menu, Pencil, Plus, Search, Trash2 } from 'lucide-react';

export interface EditableMenuItem { id: string | number; parentId?: string | number | null; label: string; url?: string; icon?: string; position?: 'top' | 'side'; sortOrder?: number; status?: 0 | 1; }
export interface EditMenuComponentProps {
  value?: EditableMenuItem[]; items?: EditableMenuItem[]; mode?: 'manager' | 'field'; maxDepth?: number;
  allowedPositions?: Array<'top' | 'side'>; valueField?: 'id' | 'url'; selectedValue?: string | number | null;
  onChange?: (items: EditableMenuItem[]) => void; onSelect?: (value: string | number, item: EditableMenuItem) => void;
  onAction?: (action: string, payload: any) => void; title?: string; className?: string;
}

export const EditMenuComponent: React.FC<EditMenuComponentProps> = ({ value, items, mode = 'manager', maxDepth = 3, allowedPositions = ['top', 'side'], valueField = 'id', selectedValue, onChange, onSelect, onAction, title = 'จัดการเมนู', className = '' }) => {
  const [data, setData] = useState<EditableMenuItem[]>(value || items || []);
  const [position, setPosition] = useState<'top' | 'side'>(allowedPositions[0] || 'top');
  const [search, setSearch] = useState('');
  const [editing, setEditing] = useState<EditableMenuItem | null>(null);
  const update = (next: EditableMenuItem[], action: string, payload?: any) => { setData(next); onChange?.(next); onAction?.(action, payload); };
  const positionItems = useMemo(() => data.filter((item) => (item.position || 'top') === position), [data, position]);
  const children = (parentId: EditableMenuItem['parentId']) => positionItems.filter((item) => (item.parentId ?? null) === (parentId ?? null)).sort((a, b) => (a.sortOrder || 0) - (b.sortOrder || 0));
  const depthOf = (item: EditableMenuItem) => { let depth = 1, parent = item.parentId; const seen = new Set([String(item.id)]); while (parent != null && !seen.has(String(parent))) { seen.add(String(parent)); depth++; parent = data.find((entry) => String(entry.id) === String(parent))?.parentId; } return depth; };
  const normalize = (source: EditableMenuItem[], parentId: EditableMenuItem['parentId']) => { const siblings = source.filter((item) => (item.parentId ?? null) === (parentId ?? null) && (item.position || 'top') === position).sort((a, b) => (a.sortOrder || 0) - (b.sortOrder || 0)); return source.map((item) => { const index = siblings.findIndex((sibling) => String(sibling.id) === String(item.id)); return index >= 0 ? { ...item, sortOrder: index + 1 } : item; }); };
  const move = (item: EditableMenuItem, direction: -1 | 1) => { const siblings = children(item.parentId); const index = siblings.findIndex((entry) => String(entry.id) === String(item.id)); const target = siblings[index + direction]; if (!target) return; update(data.map((entry) => String(entry.id) === String(item.id) ? { ...entry, sortOrder: target.sortOrder } : String(entry.id) === String(target.id) ? { ...entry, sortOrder: item.sortOrder } : entry), 'reorder', { id: item.id, direction }); };
  const indent = (item: EditableMenuItem) => { const siblings = children(item.parentId); const index = siblings.findIndex((entry) => String(entry.id) === String(item.id)); const parent = siblings[index - 1]; if (!parent || depthOf(parent) >= maxDepth) return; update(normalize(data.map((entry) => String(entry.id) === String(item.id) ? { ...entry, parentId: parent.id, sortOrder: children(parent.id).length + 1 } : entry), item.parentId), 'reparent', { id: item.id, parentId: parent.id }); };
  const outdent = (item: EditableMenuItem) => { const parent = data.find((entry) => String(entry.id) === String(item.parentId)); if (!parent) return; update(normalize(data.map((entry) => String(entry.id) === String(item.id) ? { ...entry, parentId: parent.parentId ?? null, sortOrder: (parent.sortOrder || 0) + 1 } : entry), item.parentId), 'reparent', { id: item.id, parentId: parent.parentId ?? null }); };
  const remove = (item: EditableMenuItem) => { const next = data.filter((entry) => String(entry.id) !== String(item.id)).map((entry) => String(entry.parentId) === String(item.id) ? { ...entry, parentId: item.parentId ?? null } : entry); update(normalize(next, item.parentId), 'delete', { id: item.id }); };
  const save = () => { if (!editing?.label.trim()) return; const exists = data.some((item) => String(item.id) === String(editing.id)); const next = exists ? data.map((item) => String(item.id) === String(editing.id) ? editing : item) : [...data, editing]; update(next, exists ? 'update' : 'insert', editing); setEditing(null); };
  const add = () => setEditing({ id: `new_${Date.now()}`, parentId: null, label: '', url: '#', icon: '', position, sortOrder: children(null).length + 1, status: 1 });
  const matches = (item: EditableMenuItem) => !search || `${item.label} ${item.url || ''}`.toLowerCase().includes(search.toLowerCase());
  const renderTree = (parentId: EditableMenuItem['parentId'], depth = 1): React.ReactNode => <div className={depth > 1 ? 'ms-4 ps-3 border-start' : ''}>{children(parentId).map((item) => <React.Fragment key={item.id}>{(matches(item) || children(item.id).some(matches)) && <div className={`border rounded-3 p-2 mb-2 bg-white d-flex align-items-center gap-2 ${String(selectedValue) === String(item[valueField]) ? 'border-primary shadow-sm' : ''}`}><Menu size={16} className="text-success"/><div className="flex-grow-1 min-w-0 cursor-pointer" onClick={() => onSelect?.(item[valueField] as string | number, item)}><div className="fw-semibold text-truncate">{item.label} <span className="badge bg-success ms-1">ชั้น {depth}</span></div><code className="small">{item.url || '#'}</code> <span className="small text-muted">ลำดับ {item.sortOrder || 0} · {item.status ? 'เปิด' : 'ปิด'}</span></div>{mode === 'manager' && <div className="d-flex gap-1"><button className="btn btn-sm btn-light" onClick={() => move(item, -1)}><ArrowUp size={14}/></button><button className="btn btn-sm btn-light" onClick={() => move(item, 1)}><ArrowDown size={14}/></button><button className="btn btn-sm btn-light" onClick={() => indent(item)} disabled={depth >= maxDepth}><ArrowRight size={14}/></button><button className="btn btn-sm btn-light" onClick={() => outdent(item)} disabled={depth === 1}><ArrowLeft size={14}/></button><button className={`btn btn-sm ${item.status ? 'btn-success' : 'btn-secondary'}`} onClick={() => update(data.map((entry) => String(entry.id) === String(item.id) ? { ...entry, status: entry.status ? 0 : 1 } : entry), 'toggle', { id: item.id })}><Eye size={14}/></button><button className="btn btn-sm btn-warning" onClick={() => setEditing({ ...item })}><Pencil size={14}/></button><button className="btn btn-sm btn-danger" onClick={() => remove(item)}><Trash2 size={14}/></button></div>}</div>}{renderTree(item.id, depth + 1)}</React.Fragment>)}</div>;
  return <section className={`card border-0 shadow-sm ${className}`}><header className="card-header bg-white p-3 d-flex align-items-center"><h5 className="mb-0"><Menu className="me-2 text-success"/>{title}</h5>{mode === 'manager' && <button className="btn btn-success ms-auto" onClick={add}><Plus size={16} className="me-1"/>เพิ่มเมนู</button>}</header><div className="card-body"><div className="input-group mb-3"><span className="input-group-text bg-white"><Search size={16}/></span><input className="form-control" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="ค้นหาเมนู..."/></div><div className="nav nav-tabs mb-3">{allowedPositions.map((item) => <button key={item} className={`nav-link ${position === item ? 'active fw-semibold' : ''}`} onClick={() => setPosition(item)}>{item === 'top' ? 'เมนูด้านบน' : 'เมนูด้านซ้าย'}</button>)}</div>{editing && <div className="border rounded-3 bg-light p-3 mb-3"><div className="row g-2"><div className="col-md-5"><label className="form-label small">ชื่อเมนู</label><input className="form-control" value={editing.label} onChange={(e) => setEditing({ ...editing, label: e.target.value })}/></div><div className="col-md-5"><label className="form-label small">URL / Link</label><input className="form-control" value={editing.url || ''} onChange={(e) => setEditing({ ...editing, url: e.target.value })}/></div><div className="col-md-2 d-flex align-items-end gap-1"><button className="btn btn-primary" onClick={save}>บันทึก</button><button className="btn btn-light" onClick={() => setEditing(null)}>ยกเลิก</button></div></div></div>}{renderTree(null)}</div></section>;
};
