import { describe, expect, it, vi } from "vitest";
import {
  AppSchemaError,
  applyAppSchema,
  createCollectionTableSql,
} from "@/lib/db/appSchema";
import type { TemplateDefinition } from "@/lib/template/contracts";
import { MINIMAL_TEMPLATE_DEFINITION } from "@/lib/template/examples/minimalTemplate";

const publishedDefinition = (): TemplateDefinition => {
  const definition = structuredClone(
    MINIMAL_TEMPLATE_DEFINITION,
  ) as TemplateDefinition;
  definition.template.status = "published";
  definition.template.revision = "a".repeat(64);
  return definition;
};

describe("App schema provisioner", () => {
  it("generates an additive table for typed Collection fields", () => {
    const sql = createCollectionTableSql(publishedDefinition().collections[0]);

    expect(sql).toContain('CREATE TABLE IF NOT EXISTS public."contacts"');
    expect(sql).toContain('"id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY');
    expect(sql).toContain('"name" varchar(500) NOT NULL');
    expect(sql).not.toMatch(/DROP|TRUNCATE/i);
  });

  it("rejects unsafe physical identifiers before executing SQL", () => {
    const collection = publishedDefinition().collections[0];
    collection.tableName = "contacts;drop_table";

    expect(() => createCollectionTableSql(collection)).toThrow(AppSchemaError);
  });

  it("does not add duplicate audit columns when the Collection defines them", () => {
    const collection = publishedDefinition().collections[0];
    collection.fields.push({
      id: "updated_at",
      name: "Updated at",
      type: "datetime",
      required: true,
    });

    const sql = createCollectionTableSql(collection);
    expect(sql.match(/"updated_at"/g)).toHaveLength(1);
  });

  it("applies every Collection and records the immutable revision in one transaction", async () => {
    const queries: string[] = [];
    const client = {
      query: vi.fn(async (sql: string) => {
        queries.push(sql);
        return { rowCount: null, rows: [] };
      }),
      release: vi.fn(),
    };
    const pool = { connect: vi.fn(async () => client) };

    const result = await applyAppSchema(
      pool as never,
      publishedDefinition(),
    );

    expect(result.tables).toEqual(["contacts"]);
    expect(queries[0]).toBe("BEGIN");
    expect(queries).toContain("COMMIT");
    expect(queries.some((sql) => sql.includes("sys.structure_revisions"))).toBe(true);
    expect(client.release).toHaveBeenCalledOnce();
  });
});
