#!/usr/bin/env node
/**
 * Creates or repairs the local `.env` with real secrets.
 *
 * `docker compose` now refuses to start without AUTH_SECRET and
 * PLATFORM_JWT_SECRET, because a default that is published in this repository
 * protects nothing. This script fills them in with cryptographically random
 * values and leaves every other setting alone.
 *
 * Usage:
 *   node scripts/generate-secrets.mjs            # create .env, keep existing values
 *   node scripts/generate-secrets.mjs --rotate   # replace the secrets too
 *   node scripts/generate-secrets.mjs --file .env.production
 *   node scripts/generate-secrets.mjs --print    # print values, write nothing
 */

import { randomBytes } from 'node:crypto';
import { chmodSync, existsSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import process from 'node:process';

const args = process.argv.slice(2);
const hasFlag = (name) => args.includes(`--${name}`);
const getOption = (name, fallback) => {
  const match = args.find((arg) => arg.startsWith(`--${name}=`));
  return match ? match.slice(name.length + 3) : fallback;
};

const ROTATE = hasFlag('rotate');
const PRINT_ONLY = hasFlag('print');
const TARGET = path.resolve(getOption('file', '.env'));

/** 48 random bytes → 64 base64 characters, comfortably above the 32 minimum. */
const newSecret = () => randomBytes(48).toString('base64');

/** Values published in this repo. Present in a file, they count as unset. */
const PLACEHOLDERS = new Set([
  'change-me-to-a-long-random-string-at-least-32-chars',
  'lowcode-compose-development-secret-change-me',
  'lowcode-local-jwt-secret-change-me',
  'lowcode-dev-only-insecure-session-secret',
  'dev-secret-at-least-32-characters-long-xxxx',
  'local-dev-secret-please-change-me-0123456789abcdef',
  '',
]);

const SECRET_KEYS = ['AUTH_SECRET', 'PLATFORM_JWT_SECRET'];

const DEFAULTS = {
  CORE_POSTGRES_DB: 'lowcode_core',
  CORE_POSTGRES_USER: 'lowcode_admin',
  CORE_POSTGRES_PASSWORD: 'lowcode_dev_password',
  PGADMIN_DEFAULT_EMAIL: 'admin@lowcode.dev',
  PGADMIN_DEFAULT_PASSWORD: 'pgadmin_dev_password',
  MAX_UPLOAD_BYTES: '10485760',
  SITES_HOSTNAME: '0.0.0.0',
};

function parseEnv(text) {
  const entries = new Map();
  for (const line of text.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const index = trimmed.indexOf('=');
    if (index === -1) continue;
    entries.set(trimmed.slice(0, index).trim(), trimmed.slice(index + 1).trim());
  }
  return entries;
}

const existing = existsSync(TARGET) ? parseEnv(readFileSync(TARGET, 'utf8')) : new Map();

const generated = [];
for (const key of SECRET_KEYS) {
  const current = existing.get(key);
  const needsValue = ROTATE || current === undefined || PLACEHOLDERS.has(current) || current.length < 32;
  if (needsValue) {
    existing.set(key, newSecret());
    generated.push(key);
  }
}

for (const [key, value] of Object.entries(DEFAULTS)) {
  if (!existing.has(key)) existing.set(key, value);
}

if (PRINT_ONLY) {
  for (const key of SECRET_KEYS) process.stdout.write(`${key}=${existing.get(key)}\n`);
  process.exit(0);
}

const body = [
  '# Generated by scripts/generate-secrets.mjs — do not commit this file.',
  '# Rotate the secrets with: npm run secrets -- --rotate',
  '',
  '# --- Secrets (required; docker compose refuses to start without them) ---',
  ...SECRET_KEYS.map((key) => `${key}=${existing.get(key)}`),
  '',
  '# --- Everything else ---',
  ...[...existing.entries()]
    .filter(([key]) => !SECRET_KEYS.includes(key))
    .map(([key, value]) => `${key}=${value}`),
  '',
].join('\n');

writeFileSync(TARGET, body, { mode: 0o600 });
// `mode` only applies when the file is created, so tighten an existing one too.
chmodSync(TARGET, 0o600);

const relative = path.relative(process.cwd(), TARGET) || TARGET;
if (generated.length) {
  process.stdout.write(`[secrets] wrote ${relative} — generated: ${generated.join(', ')}\n`);
} else {
  process.stdout.write(`[secrets] ${relative} already has valid secrets; nothing regenerated\n`);
}
process.stdout.write('[secrets] file permissions set to 600\n');
