'use client';
import React, { useEffect, useState } from 'react';
import { Braces, FileText, Link2, Pencil, Puzzle, Settings, Workflow } from 'lucide-react';
import type { AppRoute, StudioServiceDefinition } from '@/types';
type TabId = 'properties' | 'page' | 'events' | 'services' | 'apis';
interface PageOption { id: string; name: string }
interface Props { route: AppRoute; pageName?: string; onClose: () => void; onOpenPage?: () => void; onOpenFlow: () => void; service?: StudioServiceDefinition; availablePages?: PageOption[]; onUpdateService?: (service: StudioServiceDefinition) => Promise<void> }

const FlowBox = ({ children, tone = 'light' }: { children: React.ReactNode; tone?: 'light' | 'primary' | 'success' | 'danger' }) => <div className={`border rounded-3 px-3 py-2 text-center fw-semibold ${tone === 'light' ? 'bg-white' : `bg-${tone} text-white`}`}>{children}</div>;
export const SiteMapNodePropertyPage: React.FC<Props> = ({ route, pageName, onClose, onOpenPage, onOpenFlow, service, availablePages = [], onUpdateService }) => {
  const [activeTab, setActiveTab] = useState<TabId>('properties'); const [loginPageId, setLoginPageId] = useState(service?.bundle?.loginPageId || ''); const [adminPageId, setAdminPageId] = useState(service?.bundle?.adminPageId || ''); const [identityField, setIdentityField] = useState<'email' | 'username'>(service?.config.identityField === 'username' ? 'username' : 'email'); const [saving, setSaving] = useState(false);
  useEffect(() => { setLoginPageId(service?.bundle?.loginPageId || ''); setAdminPageId(service?.bundle?.adminPageId || ''); setIdentityField(service?.config.identityField === 'username' ? 'username' : 'email'); }, [service]);
  const tabs = [{ id: 'properties' as const, label: 'Properties', icon: Settings }, { id: 'page' as const, label: 'Pages', icon: FileText }, { id: 'events' as const, label: 'Events', icon: Workflow }, { id: 'services' as const, label: 'Services', icon: Puzzle }, { id: 'apis' as const, label: 'APIs', icon: Braces }];
  const savePages = async () => { if (!service?.bundle || !onUpdateService) return; setSaving(true); try { await onUpdateService({ ...service, config: { ...service.config, identityField }, bundle: { ...service.bundle, loginPageId, adminPageId } }); } finally { setSaving(false); } };
  const loginSteps = ['Submit Login Form', 'Find Active User', 'Verify Password', 'Load Permissions', 'Issue JWT', `Open Success Page: ${adminPageId || 'Not assigned'}`];
  return <div className="card border-0 shadow-sm h-100"><div className="card-header bg-dark text-white d-flex justify-content-between align-items-center p-3"><div><div className="small text-info fw-bold text-uppercase">{route.targetType} · Site Map Node</div><h5 className="mb-0">{route.label}</h5><code className="text-warning">{route.path}</code></div><button className="btn btn-sm btn-outline-light" onClick={onClose}>Close</button></div>
    <div className="nav nav-tabs bg-light px-3 pt-2">{tabs.map((tab) => <button key={tab.id} className={`nav-link d-flex align-items-center gap-1 ${activeTab === tab.id ? 'active fw-bold' : ''}`} onClick={() => setActiveTab(tab.id)}><tab.icon size={13}/>{tab.label}</button>)}</div>
    <div className="card-body overflow-auto p-4">
      {activeTab === 'properties' && <div className="row g-3">{[['รหัส', route.id], ['ชนิด', route.targetType], ['ชื่อที่แสดง', route.label], ['เส้นทาง', route.path], ['ปลายทาง', route.targetId || 'ยังไม่กำหนด'], ['กลุ่ม', route.containerName], ['สิทธิ์เข้าถึง', route.permission || 'สาธารณะ / ตามค่าที่สืบทอด']].map(([label, value]) => <div className="col-md-6" key={label}><label className="form-label small fw-bold text-secondary">{label}</label><div className="form-control bg-light font-monospace small">{value}</div></div>)}</div>}
      {activeTab === 'page' && service?.bundle && <div><h5>Auth Page Properties</h5><p className="text-muted">Select pages and the identity field used by this service. Site Map child nodes follow these properties.</p><div className="row g-3">{[['Login Page', loginPageId, setLoginPageId], ['Success / Admin Page', adminPageId, setAdminPageId]].map(([label, value, setter]) => <div className="col-md-6" key={String(label)}><label className="form-label fw-semibold">{String(label)}</label><select className="form-select" value={String(value)} onChange={(event) => (setter as React.Dispatch<React.SetStateAction<string>>)(event.target.value)}><option value="">Not assigned</option>{availablePages.map((page) => <option key={page.id} value={page.id}>{page.name}</option>)}</select></div>)}<div className="col-md-6"><label className="form-label fw-semibold">Login identity</label><select className="form-select" value={identityField} onChange={(event) => setIdentityField(event.target.value === 'username' ? 'username' : 'email')}><option value="email">Email</option><option value="username">Username</option></select><div className="form-text">Updates the generated Login form and Auth service together.</div></div></div><button className="btn btn-primary mt-3" disabled={saving} onClick={() => void savePages()}>{saving ? 'Saving...' : 'Save Page Properties'}</button></div>}
      {activeTab === 'page' && !service?.bundle && <div><h5>Page Target</h5><p>{pageName || route.targetId || 'Not assigned'}</p><button className="btn btn-primary" disabled={!onOpenPage} onClick={onOpenPage}>Open Designer</button></div>}
      {activeTab === 'events' && <div><h5>{service?.bundle ? 'Auth Event Flowchart' : 'Node Events'}</h5>{service?.bundle && <div className="border rounded-3 bg-light p-3 mb-3"><div className="small fw-bold text-primary mb-2">LOGIN FLOW</div><div className="d-flex flex-column" style={{ maxWidth: 650 }}>{loginSteps.map((label, index) => <React.Fragment key={label}><FlowBox tone={index === 0 ? 'primary' : index === loginSteps.length - 1 ? 'success' : 'light'}>{label}</FlowBox>{index < loginSteps.length - 1 && <div className="text-center text-warning fs-5 lh-1">↓</div>}</React.Fragment>)}</div><div className="small fw-bold text-danger mt-4 mb-2">LOGOUT FLOW</div><div className="d-flex align-items-center flex-wrap gap-2"><FlowBox tone="danger">Click Logout</FlowBox><b className="text-danger">→</b><FlowBox>Clear JWT</FlowBox><b className="text-danger">→</b><FlowBox tone="primary">Open Login Page: {loginPageId || 'Not assigned'}</FlowBox></div></div>}<button className="btn btn-warning" onClick={onOpenFlow}><Pencil size={14} className="me-1"/>Edit Flow</button></div>}
      {activeTab === 'services' && <div><h5>Assigned Service</h5><p>{service ? `${service.name} · ${(service.provider || service.serviceRef?.serviceKey || service.kind).toUpperCase()} · Mother logic` : 'No binding'}</p><button className="btn btn-outline-primary" onClick={onOpenFlow}><Link2 size={14} className="me-1"/>Edit Service Flow</button></div>}
      {activeTab === 'apis' && <div><h5>API Bindings</h5><p>API calls are configured in the flow editor.</p><button className="btn btn-outline-info" onClick={onOpenFlow}>Edit API Flow</button></div>}
    </div></div>;
};
