'use client';

import React, { useState } from 'react';
import { ChevronDown, ChevronRight, Plus, Trash2 } from 'lucide-react';
import type { SlideMenuItem } from '@/components/shared/SlideMenuComponent';
import type { RuntimeMenuAction } from '@/types';

type PageOption = { id: string; name: string; routePath?: string };
const makeItem = (): SlideMenuItem => ({ id: `menu-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`, label: 'เมนูใหม่', type: 'item', action: { type: 'none' } });
const makeAction = (type: RuntimeMenuAction['type']): RuntimeMenuAction => type === 'switchContent' ? { type, contentId: '' } : type === 'navigatePage' ? { type, pageId: '' } : type === 'navigateRoute' || type === 'openRoute' ? { type: 'navigateRoute', routeId: '' } : type === 'openExternal' ? { type, url: '', newTab: false } : type === 'runService' ? { type, serviceId: '' } : type === 'callApi' ? { type, url: '', method: 'GET' } : { type: 'none' };

export const SlideMenuRouteBuilder: React.FC<{ items: SlideMenuItem[]; pages?: PageOption[]; onChange: (items: SlideMenuItem[]) => void }> = ({ items, pages = [], onChange }) => {
  const [open, setOpen] = useState<Record<string, boolean>>({});
  const [advanced, setAdvanced] = useState(false);
  const [json, setJson] = useState(() => JSON.stringify(items, null, 2));
  const editAt = (path: number[], value: SlideMenuItem | null) => {
    const walk = (list: SlideMenuItem[], depth: number): SlideMenuItem[] => list.flatMap((item, index) => index !== path[depth] ? [item] : depth === path.length - 1 ? (value ? [value] : []) : [{ ...item, children: walk(item.children || [], depth + 1) }]);
    onChange(walk(items, 0));
  };
  const targetEditor = (action: RuntimeMenuAction, change: (action: RuntimeMenuAction) => void) => {
    if (action.type === 'switchContent') return <><input className="form-control form-control-sm" list="menu-content-pages" value={action.contentId} placeholder="Page, Form, Collection หรือ Component ID" onChange={(e) => change({ ...action, contentId: e.target.value })}/><datalist id="menu-content-pages">{pages.map((page) => <option key={page.id} value={page.id}>{page.name}</option>)}</datalist><small className="text-muted">สลับเฉพาะ Content Outlet โดยไม่เปลี่ยนหน้า</small></>;
    if (action.type === 'navigatePage') return <select className="form-select form-select-sm" value={action.pageId} onChange={(e) => change({ ...action, pageId: e.target.value })}><option value="">Select Page...</option>{pages.map((page) => <option key={page.id} value={page.id}>{page.name}</option>)}</select>;
    if (action.type === 'navigateRoute' || action.type === 'openRoute') return <input className="form-control form-control-sm" value={action.routeId} placeholder="Route ID" onChange={(e) => change({ ...action, routeId: e.target.value })}/>;
    if (action.type === 'openExternal') return <div className="input-group input-group-sm"><input className="form-control" value={action.url} placeholder="https://..." onChange={(e) => change({ ...action, url: e.target.value })}/><span className="input-group-text"><input type="checkbox" checked={action.newTab !== false} onChange={(e) => change({ ...action, newTab: e.target.checked })}/> New tab</span></div>;
    if (action.type === 'runService') return <input className="form-control form-control-sm" value={action.serviceId} placeholder="Service ID" onChange={(e) => change({ ...action, serviceId: e.target.value })}/>;
    if (action.type === 'callApi') return <div className="input-group input-group-sm"><select className="form-select" style={{ maxWidth: 100 }} value={action.method || 'GET'} onChange={(e) => change({ ...action, method: e.target.value as 'GET' })}>{['GET','POST','PUT','PATCH','DELETE'].map((method) => <option key={method}>{method}</option>)}</select><input className="form-control" value={action.url || ''} placeholder="/api/..." onChange={(e) => change({ ...action, url: e.target.value })}/></div>;
    return <div className="text-muted small">No target</div>;
  };
  const render = (list: SlideMenuItem[], parent: number[] = []): React.ReactNode => list.map((item, index) => {
    const path = [...parent, index]; const expanded = open[item.id] !== false;
    const update = (patch: Partial<SlideMenuItem>) => editAt(path, { ...item, ...patch });
    const action = (item.action || (item.href ? (/^https?:\/\//.test(item.href) ? { type: 'openExternal', url: item.href } : { type: 'switchContent', contentId: item.href }) : { type: 'none' })) as RuntimeMenuAction;
    return <div key={item.id} className="mb-2"><div className="border rounded-3 bg-white overflow-hidden"><div className="d-flex align-items-center gap-2 p-2 bg-light border-bottom"><button className="btn btn-sm border-0 p-0" onClick={() => setOpen((state) => ({ ...state, [item.id]: !expanded }))}>{expanded ? <ChevronDown size={14}/> : <ChevronRight size={14}/>}</button><b className="small flex-grow-1">{item.label}</b><span className="badge bg-primary bg-opacity-10 text-primary">{action.type}</span><button className="btn btn-sm btn-outline-danger" onClick={() => editAt(path, null)}><Trash2 size={12}/></button></div>{expanded && <div className="p-3"><div className="row g-2"><div className="col-md-5"><label className="form-label small mb-1">ชื่อเมนู</label><input className="form-control form-control-sm" value={item.label} onChange={(e) => update({ label: e.target.value })}/></div><div className="col-md-3"><label className="form-label small mb-1">Node Type</label><select className="form-select form-select-sm" value={item.type || 'item'} onChange={(e) => update({ type: e.target.value as 'item' | 'section' })}><option value="item">Menu Item</option><option value="section">Section</option></select></div><div className="col-md-4"><label className="form-label small mb-1">Permission</label><input className="form-control form-control-sm" value={item.permission || ''} onChange={(e) => update({ permission: e.target.value || undefined })}/></div>{item.type !== 'section' && <><div className="col-md-4"><label className="form-label small mb-1">Action Type</label><select className="form-select form-select-sm" value={action.type === 'openRoute' ? 'navigateRoute' : action.type} onChange={(e) => update({ action: makeAction(e.target.value as RuntimeMenuAction['type']) })}><option value="switchContent">Switch Content</option><option value="navigatePage">Navigate Page</option><option value="navigateRoute">Navigate Route</option><option value="openExternal">Open External</option><option value="runService">Run Service</option><option value="callApi">Call API</option><option value="none">No action</option></select></div><div className="col-md-8"><label className="form-label small mb-1">Target</label>{targetEditor(action, (next) => update({ action: next }))}</div></>}</div><button className="btn btn-sm btn-outline-primary mt-3" onClick={() => update({ children: [...(item.children || []), makeItem()] })}><Plus size={12}/> เพิ่มเมนูย่อย</button></div>}</div>{item.children?.length ? <div className="ms-4 ps-3 mt-2 border-start">{render(item.children, path)}</div> : null}</div>;
  });
  return <div><div className="d-flex justify-content-between mb-3"><div><h6 className="mb-0">Menu Items & Action Builder</h6><small className="text-muted">Switch Content และ Navigation อยู่ร่วมกันได้</small></div><div className="d-flex gap-2"><button className="btn btn-sm btn-outline-secondary" onClick={() => { setJson(JSON.stringify(items, null, 2)); setAdvanced(!advanced); }}>JSON</button><button className="btn btn-sm btn-primary" onClick={() => onChange([...items, makeItem()])}><Plus size={12}/> เพิ่มเมนู</button></div></div>{advanced ? <><textarea className="form-control font-monospace" rows={18} value={json} onChange={(e) => setJson(e.target.value)}/><button className="btn btn-warning btn-sm mt-2" onClick={() => { try { const value = JSON.parse(json); if (!Array.isArray(value)) throw new Error(); onChange(value); setAdvanced(false); } catch { window.alert('Menu Items JSON ไม่ถูกต้อง'); } }}>Apply JSON</button></> : render(items)}</div>;
};
